namespace TicketPro.Logins
{
    partial class CambiarPassword
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CambiarPassword));
            this.pnlBody = new System.Windows.Forms.Panel();
            this.tblLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblNueva = new System.Windows.Forms.Label();
            this.txtNueva = new System.Windows.Forms.TextBox();
            this.lblConfirmar = new System.Windows.Forms.Label();
            this.txtConfirmar = new System.Windows.Forms.TextBox();
            this.lblRequisitos = new System.Windows.Forms.Label();
            this.pnlBotones = new System.Windows.Forms.Panel();
            this.btnGuardar = new System.Windows.Forms.Button();
            this.btnVolverLogin = new System.Windows.Forms.Button();
            this.lblEstado = new System.Windows.Forms.Label();
            this.pnlHeader = new System.Windows.Forms.Panel();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.lblSubtitulo = new System.Windows.Forms.Label();
            this.pnlBody.SuspendLayout();
            this.tblLayout.SuspendLayout();
            this.pnlBotones.SuspendLayout();
            this.pnlHeader.SuspendLayout();
            this.SuspendLayout();
            this.pnlBody.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.pnlBody.Controls.Add(this.tblLayout);
            this.pnlBody.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlBody.Location = new System.Drawing.Point(0, 100);
            this.pnlBody.Name = "pnlBody";
            this.pnlBody.Padding = new System.Windows.Forms.Padding(60, 40, 60, 40);
            this.pnlBody.Size = new System.Drawing.Size(600, 500);
            this.pnlBody.TabIndex = 1;
            this.tblLayout.ColumnCount = 1;
            this.tblLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tblLayout.Controls.Add(this.lblNueva, 0, 0);
            this.tblLayout.Controls.Add(this.txtNueva, 0, 1);
            this.tblLayout.Controls.Add(this.lblConfirmar, 0, 2);
            this.tblLayout.Controls.Add(this.txtConfirmar, 0, 3);
            this.tblLayout.Controls.Add(this.lblRequisitos, 0, 4);
            this.tblLayout.Controls.Add(this.pnlBotones, 0, 5);
            this.tblLayout.Controls.Add(this.lblEstado, 0, 6);
            this.tblLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tblLayout.Location = new System.Drawing.Point(60, 40);
            this.tblLayout.Name = "tblLayout";
            this.tblLayout.RowCount = 7;
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 100F));
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.tblLayout.Size = new System.Drawing.Size(480, 420);
            this.tblLayout.TabIndex = 0;
            this.lblNueva.AutoSize = true;
            this.lblNueva.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblNueva.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblNueva.ForeColor = System.Drawing.Color.White;
            this.lblNueva.Location = new System.Drawing.Point(3, 0);
            this.lblNueva.Name = "lblNueva";
            this.lblNueva.Size = new System.Drawing.Size(474, 30);
            this.lblNueva.TabIndex = 0;
            this.lblNueva.Text = "Nueva Contrasena";
            this.lblNueva.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.txtNueva.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            this.txtNueva.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtNueva.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtNueva.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.txtNueva.ForeColor = System.Drawing.Color.White;
            this.txtNueva.Location = new System.Drawing.Point(3, 35);
            this.txtNueva.Margin = new System.Windows.Forms.Padding(3, 5, 3, 3);
            this.txtNueva.Name = "txtNueva";
            this.txtNueva.PasswordChar = '●';
            this.txtNueva.Size = new System.Drawing.Size(474, 27);
            this.txtNueva.TabIndex = 1;
            this.lblConfirmar.AutoSize = true;
            this.lblConfirmar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblConfirmar.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblConfirmar.ForeColor = System.Drawing.Color.White;
            this.lblConfirmar.Location = new System.Drawing.Point(3, 80);
            this.lblConfirmar.Name = "lblConfirmar";
            this.lblConfirmar.Size = new System.Drawing.Size(474, 30);
            this.lblConfirmar.TabIndex = 2;
            this.lblConfirmar.Text = "Confirmar Contrasena";
            this.lblConfirmar.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.txtConfirmar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            this.txtConfirmar.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtConfirmar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtConfirmar.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.txtConfirmar.ForeColor = System.Drawing.Color.White;
            this.txtConfirmar.Location = new System.Drawing.Point(3, 115);
            this.txtConfirmar.Margin = new System.Windows.Forms.Padding(3, 5, 3, 3);
            this.txtConfirmar.Name = "txtConfirmar";
            this.txtConfirmar.PasswordChar = '●';
            this.txtConfirmar.Size = new System.Drawing.Size(474, 27);
            this.txtConfirmar.TabIndex = 3;
            this.lblRequisitos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRequisitos.Font = new System.Drawing.Font("Segoe UI", 8.5F);
            this.lblRequisitos.ForeColor = System.Drawing.Color.LightGray;
            this.lblRequisitos.Location = new System.Drawing.Point(3, 160);
            this.lblRequisitos.Name = "lblRequisitos";
            this.lblRequisitos.Padding = new System.Windows.Forms.Padding(0, 5, 0, 0);
            this.lblRequisitos.Size = new System.Drawing.Size(474, 50);
            this.lblRequisitos.TabIndex = 4;
            this.lblRequisitos.Text = "La Contrasena debe tener al menos 8 caracteres, incluir mayusculas, minusculas y " +
    "numeros.";
            this.pnlBotones.Controls.Add(this.btnGuardar);
            this.pnlBotones.Controls.Add(this.btnVolverLogin);
            this.pnlBotones.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlBotones.Location = new System.Drawing.Point(3, 213);
            this.pnlBotones.Name = "pnlBotones";
            this.pnlBotones.Padding = new System.Windows.Forms.Padding(0, 10, 0, 0);
            this.pnlBotones.Size = new System.Drawing.Size(474, 94);
            this.pnlBotones.TabIndex = 5;
            this.btnGuardar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(167)))), ((int)(((byte)(69)))));
            this.btnGuardar.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnGuardar.FlatAppearance.BorderSize = 0;
            this.btnGuardar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnGuardar.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold);
            this.btnGuardar.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.Location = new System.Drawing.Point(0, 10);
            this.btnGuardar.Name = "btnGuardar";
            this.btnGuardar.Size = new System.Drawing.Size(474, 40);
            this.btnGuardar.TabIndex = 0;
            this.btnGuardar.Text = "Guardar nueva Contrasena";
            this.btnGuardar.UseVisualStyleBackColor = false;
            this.btnGuardar.Click += new System.EventHandler(this.btnGuardar_Click);
            this.btnVolverLogin.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.btnVolverLogin.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.btnVolverLogin.FlatAppearance.BorderSize = 0;
            this.btnVolverLogin.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnVolverLogin.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnVolverLogin.ForeColor = System.Drawing.Color.White;
            this.btnVolverLogin.Location = new System.Drawing.Point(0, 66);
            this.btnVolverLogin.Name = "btnVolverLogin";
            this.btnVolverLogin.Size = new System.Drawing.Size(474, 28);
            this.btnVolverLogin.TabIndex = 1;
            this.btnVolverLogin.Text = "Volver al Login";
            this.btnVolverLogin.UseVisualStyleBackColor = false;
            this.btnVolverLogin.Click += new System.EventHandler(this.btnVolverLogin_Click);
            this.lblEstado.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblEstado.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblEstado.ForeColor = System.Drawing.Color.LightCoral;
            this.lblEstado.Location = new System.Drawing.Point(3, 310);
            this.lblEstado.Name = "lblEstado";
            this.lblEstado.Size = new System.Drawing.Size(474, 110);
            this.lblEstado.TabIndex = 6;
            this.lblEstado.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.pnlHeader.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(55)))));
            this.pnlHeader.Controls.Add(this.lblTitulo);
            this.pnlHeader.Controls.Add(this.lblSubtitulo);
            this.pnlHeader.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlHeader.Location = new System.Drawing.Point(0, 0);
            this.pnlHeader.Name = "pnlHeader";
            this.pnlHeader.Size = new System.Drawing.Size(600, 100);
            this.pnlHeader.TabIndex = 0;
            this.lblTitulo.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblTitulo.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            this.lblTitulo.ForeColor = System.Drawing.Color.White;
            this.lblTitulo.Location = new System.Drawing.Point(0, 0);
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.Size = new System.Drawing.Size(600, 50);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.Text = "Cambiar Contrasena";
            this.lblTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblSubtitulo.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.lblSubtitulo.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lblSubtitulo.ForeColor = System.Drawing.Color.Gainsboro;
            this.lblSubtitulo.Location = new System.Drawing.Point(0, 50);
            this.lblSubtitulo.Name = "lblSubtitulo";
            this.lblSubtitulo.Padding = new System.Windows.Forms.Padding(40, 0, 40, 0);
            this.lblSubtitulo.Size = new System.Drawing.Size(600, 50);
            this.lblSubtitulo.TabIndex = 1;
            this.lblSubtitulo.Text = "Ingresa tu nueva Contrasena. Debe cumplir con los requisitos de seguridad.";
            this.lblSubtitulo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.ClientSize = new System.Drawing.Size(600, 600);
            this.Controls.Add(this.pnlBody);
            this.Controls.Add(this.pnlHeader);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MinimumSize = new System.Drawing.Size(500, 550);
            this.Name = "CambiarPassword";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Cambio de Contrasena";
            this.pnlBody.ResumeLayout(false);
            this.tblLayout.ResumeLayout(false);
            this.tblLayout.PerformLayout();
            this.pnlBotones.ResumeLayout(false);
            this.pnlHeader.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        private System.Windows.Forms.Panel pnlHeader;
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.Label lblSubtitulo;
        private System.Windows.Forms.Panel pnlBody;
        private System.Windows.Forms.TableLayoutPanel tblLayout;
        private System.Windows.Forms.Label lblNueva;
        private System.Windows.Forms.TextBox txtNueva;
        private System.Windows.Forms.Label lblConfirmar;
        private System.Windows.Forms.TextBox txtConfirmar;
        private System.Windows.Forms.Label lblRequisitos;
        private System.Windows.Forms.Panel pnlBotones;
        private System.Windows.Forms.Button btnGuardar;
        private System.Windows.Forms.Button btnVolverLogin;
        private System.Windows.Forms.Label lblEstado;
    }
}
