using System.Drawing;
using System.Windows.Forms;
namespace TicketPro
{
    partial class LogIn
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Inicializacion de formulario
        private void InitializeComponent()
        {
            this.pnlMain = new System.Windows.Forms.Panel();
            this.pnlLeft = new System.Windows.Forms.Panel();
            this.lblAppVersion = new System.Windows.Forms.Label();
            this.lblAppSubtitle = new System.Windows.Forms.Label();
            this.lblAppTitle = new System.Windows.Forms.Label();
            this.pnlRight = new System.Windows.Forms.Panel();
            this.pnlTopBar = new System.Windows.Forms.Panel();
            this.cmbIdioma = new System.Windows.Forms.ComboBox();
            this.pnlForm = new System.Windows.Forms.Panel();
            this.labelTitle = new System.Windows.Forms.Label();
            this.pnlUserInput = new System.Windows.Forms.Panel();
            this.txtUser = new System.Windows.Forms.TextBox();
            this.labelUsername = new System.Windows.Forms.Label();
            this.pnlPassInput = new System.Windows.Forms.Panel();
            this.txtPass = new System.Windows.Forms.TextBox();
            this.labelPassword = new System.Windows.Forms.Label();
            this.labelForgot = new System.Windows.Forms.Label();
            this.BtnLogin = new System.Windows.Forms.Button();
            this.lblOrSeparator = new System.Windows.Forms.Label();
            this.BtnRegister = new System.Windows.Forms.Button();
            this.pnlMain.SuspendLayout();
            this.pnlLeft.SuspendLayout();
            this.pnlRight.SuspendLayout();
            this.pnlTopBar.SuspendLayout();
            this.pnlForm.SuspendLayout();
            this.pnlUserInput.SuspendLayout();
            this.pnlPassInput.SuspendLayout();
            this.SuspendLayout();
            this.pnlMain.BackColor = System.Drawing.Color.White;
            this.pnlMain.Controls.Add(this.pnlLeft);
            this.pnlMain.Controls.Add(this.pnlRight);
            this.pnlMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlMain.Location = new System.Drawing.Point(0, 0);
            this.pnlMain.Name = "pnlMain";
            this.pnlMain.Size = new System.Drawing.Size(1000, 600);
            this.pnlMain.TabIndex = 0;
            this.pnlLeft.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.pnlLeft.Controls.Add(this.lblAppVersion);
            this.pnlLeft.Controls.Add(this.lblAppSubtitle);
            this.pnlLeft.Controls.Add(this.lblAppTitle);
            this.pnlLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this.pnlLeft.Location = new System.Drawing.Point(0, 0);
            this.pnlLeft.Name = "pnlLeft";
            this.pnlLeft.Size = new System.Drawing.Size(400, 600);
            this.pnlLeft.TabIndex = 0;
            this.lblAppVersion.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.lblAppVersion.AutoSize = true;
            this.lblAppVersion.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblAppVersion.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(220)))));
            this.lblAppVersion.Location = new System.Drawing.Point(30, 560);
            this.lblAppVersion.Name = "lblAppVersion";
            this.lblAppVersion.Size = new System.Drawing.Size(0, 15);
            this.lblAppVersion.TabIndex = 2;
            this.lblAppSubtitle.AutoSize = true;
            this.lblAppSubtitle.Font = new System.Drawing.Font("Segoe UI Light", 14F);
            this.lblAppSubtitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(220)))), ((int)(((byte)(240)))));
            this.lblAppSubtitle.Location = new System.Drawing.Point(30, 330);
            this.lblAppSubtitle.MaximumSize = new System.Drawing.Size(340, 0);
            this.lblAppSubtitle.Name = "lblAppSubtitle";
            this.lblAppSubtitle.Size = new System.Drawing.Size(249, 25);
            this.lblAppSubtitle.TabIndex = 1;
            this.lblAppSubtitle.Text = "Sistema de Gestion de Tickets\r\n";
            this.lblAppTitle.AutoSize = true;
            this.lblAppTitle.Font = new System.Drawing.Font("Segoe UI", 48F, System.Drawing.FontStyle.Bold);
            this.lblAppTitle.ForeColor = System.Drawing.Color.White;
            this.lblAppTitle.Location = new System.Drawing.Point(20, 240);
            this.lblAppTitle.Name = "lblAppTitle";
            this.lblAppTitle.Size = new System.Drawing.Size(350, 86);
            this.lblAppTitle.TabIndex = 0;
            this.lblAppTitle.Text = "TicketsPro";
            this.pnlRight.BackColor = System.Drawing.Color.White;
            this.pnlRight.Controls.Add(this.pnlTopBar);
            this.pnlRight.Controls.Add(this.pnlForm);
            this.pnlRight.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlRight.Location = new System.Drawing.Point(0, 0);
            this.pnlRight.Name = "pnlRight";
            this.pnlRight.Size = new System.Drawing.Size(1000, 600);
            this.pnlRight.TabIndex = 1;
            this.pnlTopBar.Controls.Add(this.cmbIdioma);
            this.pnlTopBar.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlTopBar.Location = new System.Drawing.Point(0, 0);
            this.pnlTopBar.Name = "pnlTopBar";
            this.pnlTopBar.Size = new System.Drawing.Size(1000, 50);
            this.pnlTopBar.TabIndex = 0;
            this.cmbIdioma.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.cmbIdioma.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(250)))), ((int)(((byte)(250)))));
            this.cmbIdioma.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbIdioma.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbIdioma.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cmbIdioma.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(80)))), ((int)(((byte)(80)))), ((int)(((byte)(80)))));
            this.cmbIdioma.FormattingEnabled = true;
            this.cmbIdioma.Location = new System.Drawing.Point(800, 13);
            this.cmbIdioma.Name = "cmbIdioma";
            this.cmbIdioma.Size = new System.Drawing.Size(188, 23);
            this.cmbIdioma.TabIndex = 9;
            this.pnlForm.Controls.Add(this.labelTitle);
            this.pnlForm.Controls.Add(this.pnlUserInput);
            this.pnlForm.Controls.Add(this.labelUsername);
            this.pnlForm.Controls.Add(this.pnlPassInput);
            this.pnlForm.Controls.Add(this.labelPassword);
            this.pnlForm.Controls.Add(this.labelForgot);
            this.pnlForm.Controls.Add(this.BtnLogin);
            this.pnlForm.Controls.Add(this.lblOrSeparator);
            this.pnlForm.Controls.Add(this.BtnRegister);
            this.pnlForm.Location = new System.Drawing.Point(430, 80);
            this.pnlForm.Name = "pnlForm";
            this.pnlForm.Size = new System.Drawing.Size(474, 467);
            this.pnlForm.TabIndex = 1;
            this.labelTitle.AutoSize = true;
            this.labelTitle.Font = new System.Drawing.Font("Segoe UI", 28F, System.Drawing.FontStyle.Bold);
            this.labelTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.labelTitle.Location = new System.Drawing.Point(23, 15);
            this.labelTitle.Name = "labelTitle";
            this.labelTitle.Size = new System.Drawing.Size(258, 51);
            this.labelTitle.TabIndex = 1;
            this.labelTitle.Text = "Iniciar Sesion";
            this.pnlUserInput.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(245)))));
            this.pnlUserInput.Controls.Add(this.txtUser);
            this.pnlUserInput.Location = new System.Drawing.Point(23, 125);
            this.pnlUserInput.Name = "pnlUserInput";
            this.pnlUserInput.Size = new System.Drawing.Size(400, 45);
            this.pnlUserInput.TabIndex = 3;
            this.txtUser.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(245)))));
            this.txtUser.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.txtUser.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.txtUser.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.txtUser.Location = new System.Drawing.Point(9, 12);
            this.txtUser.Name = "txtUser";
            this.txtUser.Size = new System.Drawing.Size(376, 22);
            this.txtUser.TabIndex = 2;
            this.labelUsername.AutoSize = true;
            this.labelUsername.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.labelUsername.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.labelUsername.Location = new System.Drawing.Point(23, 100);
            this.labelUsername.Name = "labelUsername";
            this.labelUsername.Size = new System.Drawing.Size(141, 19);
            this.labelUsername.TabIndex = 4;
            this.labelUsername.Text = "Nombre de Usuario";
            this.pnlPassInput.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(245)))));
            this.pnlPassInput.Controls.Add(this.txtPass);
            this.pnlPassInput.Location = new System.Drawing.Point(23, 210);
            this.pnlPassInput.Name = "pnlPassInput";
            this.pnlPassInput.Size = new System.Drawing.Size(400, 45);
            this.pnlPassInput.TabIndex = 5;
            this.txtPass.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(245)))));
            this.txtPass.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.txtPass.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.txtPass.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.txtPass.Location = new System.Drawing.Point(9, 12);
            this.txtPass.Name = "txtPass";
            this.txtPass.PasswordChar = '●';
            this.txtPass.Size = new System.Drawing.Size(376, 22);
            this.txtPass.TabIndex = 3;
            this.labelPassword.AutoSize = true;
            this.labelPassword.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.labelPassword.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.labelPassword.Location = new System.Drawing.Point(23, 185);
            this.labelPassword.Name = "labelPassword";
            this.labelPassword.Size = new System.Drawing.Size(84, 19);
            this.labelPassword.TabIndex = 5;
            this.labelPassword.Text = "Contrasena";
            this.labelForgot.AutoSize = true;
            this.labelForgot.Cursor = System.Windows.Forms.Cursors.Hand;
            this.labelForgot.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.labelForgot.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(81)))), ((int)(((byte)(181)))));
            this.labelForgot.Location = new System.Drawing.Point(23, 265);
            this.labelForgot.Name = "labelForgot";
            this.labelForgot.Size = new System.Drawing.Size(138, 15);
            this.labelForgot.TabIndex = 6;
            this.labelForgot.Text = "Olvidaste tu Contrasena?";
            this.labelForgot.Click += new System.EventHandler(this.label4_Click);
            this.BtnLogin.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.BtnLogin.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnLogin.FlatAppearance.BorderSize = 0;
            this.BtnLogin.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.BtnLogin.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.BtnLogin.ForeColor = System.Drawing.Color.White;
            this.BtnLogin.Location = new System.Drawing.Point(23, 300);
            this.BtnLogin.Name = "BtnLogin";
            this.BtnLogin.Size = new System.Drawing.Size(400, 50);
            this.BtnLogin.TabIndex = 0;
            this.BtnLogin.Text = "Iniciar Sesion";
            this.BtnLogin.UseVisualStyleBackColor = false;
            this.BtnLogin.Click += new System.EventHandler(this.BtnLogin_Click);
            this.lblOrSeparator.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblOrSeparator.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.lblOrSeparator.Location = new System.Drawing.Point(23, 365);
            this.lblOrSeparator.Name = "lblOrSeparator";
            this.lblOrSeparator.Size = new System.Drawing.Size(400, 20);
            this.lblOrSeparator.TabIndex = 7;
            this.lblOrSeparator.Text = "-------  o  -------";
            this.lblOrSeparator.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnRegister.BackColor = System.Drawing.Color.White;
            this.BtnRegister.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnRegister.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(81)))), ((int)(((byte)(181)))));
            this.BtnRegister.FlatAppearance.BorderSize = 2;
            this.BtnRegister.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.BtnRegister.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold);
            this.BtnRegister.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.BtnRegister.Location = new System.Drawing.Point(23, 400);
            this.BtnRegister.Name = "BtnRegister";
            this.BtnRegister.Size = new System.Drawing.Size(400, 50);
            this.BtnRegister.TabIndex = 8;
            this.BtnRegister.Text = "Crear una cuenta";
            this.BtnRegister.UseVisualStyleBackColor = false;
            this.BtnRegister.Click += new System.EventHandler(this.BtnRegister_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1000, 600);
            this.Controls.Add(this.pnlMain);
            this.MinimumSize = new System.Drawing.Size(900, 500);
            this.Name = "LogIn";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "TicketsPro - Iniciar Sesion";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.LogIn_FormClosed);
            this.pnlMain.ResumeLayout(false);
            this.pnlLeft.ResumeLayout(false);
            this.pnlLeft.PerformLayout();
            this.pnlRight.ResumeLayout(false);
            this.pnlTopBar.ResumeLayout(false);
            this.pnlForm.ResumeLayout(false);
            this.pnlForm.PerformLayout();
            this.pnlUserInput.ResumeLayout(false);
            this.pnlUserInput.PerformLayout();
            this.pnlPassInput.ResumeLayout(false);
            this.pnlPassInput.PerformLayout();
            this.ResumeLayout(false);
        }
        #endregion
        private Panel pnlMain;
        private Panel pnlLeft;
        private Label lblAppTitle;
        private Label lblAppSubtitle;
        private Label lblAppVersion;
        private Panel pnlRight;
        private Panel pnlTopBar;
        private ComboBox cmbIdioma;
        private Panel pnlForm;
        private Label labelTitle;
        private Panel pnlUserInput;
        private TextBox txtUser;
        private Label labelUsername;
        private Panel pnlPassInput;
        private TextBox txtPass;
        private Label labelPassword;
        private Label labelForgot;
        private Button BtnLogin;
        private Label lblOrSeparator;
        private Button BtnRegister;
    }
}
