using System.Drawing;
using System.Windows.Forms;
namespace TicketPro
{
    partial class Register
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.pnlMain = new System.Windows.Forms.Panel();
            this.pnlContent = new System.Windows.Forms.Panel();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.lblSubtitulo = new System.Windows.Forms.Label();
            this.lblEmail = new System.Windows.Forms.Label();
            this.pnlEmailInput = new System.Windows.Forms.Panel();
            this.lblEmailIcon = new System.Windows.Forms.Label();
            this.txtEmail = new System.Windows.Forms.TextBox();
            this.lblUser = new System.Windows.Forms.Label();
            this.pnlUserInput = new System.Windows.Forms.Panel();
            this.lblUserIcon = new System.Windows.Forms.Label();
            this.txtUser = new System.Windows.Forms.TextBox();
            this.lblPassword = new System.Windows.Forms.Label();
            this.pnlPassInput = new System.Windows.Forms.Panel();
            this.lblPassIcon = new System.Windows.Forms.Label();
            this.txtPass = new System.Windows.Forms.TextBox();
            this.lblRequisitos = new System.Windows.Forms.Label();
            this.BtnRegister = new System.Windows.Forms.Button();
            this.btnVolverLogin = new System.Windows.Forms.Button();
            this.pnlMain.SuspendLayout();
            this.pnlContent.SuspendLayout();
            this.pnlEmailInput.SuspendLayout();
            this.pnlUserInput.SuspendLayout();
            this.pnlPassInput.SuspendLayout();
            this.SuspendLayout();
            this.pnlMain.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.pnlMain.Controls.Add(this.pnlContent);
            this.pnlMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlMain.Location = new System.Drawing.Point(0, 0);
            this.pnlMain.Name = "pnlMain";
            this.pnlMain.Padding = new System.Windows.Forms.Padding(40);
            this.pnlMain.Size = new System.Drawing.Size(600, 650);
            this.pnlMain.TabIndex = 0;
            this.pnlContent.BackColor = System.Drawing.Color.White;
            this.pnlContent.Controls.Add(this.lblTitulo);
            this.pnlContent.Controls.Add(this.lblSubtitulo);
            this.pnlContent.Controls.Add(this.lblEmail);
            this.pnlContent.Controls.Add(this.pnlEmailInput);
            this.pnlContent.Controls.Add(this.lblUser);
            this.pnlContent.Controls.Add(this.pnlUserInput);
            this.pnlContent.Controls.Add(this.lblPassword);
            this.pnlContent.Controls.Add(this.pnlPassInput);
            this.pnlContent.Controls.Add(this.lblRequisitos);
            this.pnlContent.Controls.Add(this.BtnRegister);
            this.pnlContent.Controls.Add(this.btnVolverLogin);
            this.pnlContent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlContent.Location = new System.Drawing.Point(40, 40);
            this.pnlContent.Name = "pnlContent";
            this.pnlContent.Padding = new System.Windows.Forms.Padding(50, 40, 50, 40);
            this.pnlContent.Size = new System.Drawing.Size(520, 570);
            this.pnlContent.TabIndex = 0;
            this.lblTitulo.AutoSize = true;
            this.lblTitulo.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold);
            this.lblTitulo.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.lblTitulo.Location = new System.Drawing.Point(50, 40);
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.Size = new System.Drawing.Size(214, 45);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.Text = "Crear Cuenta";
            this.lblSubtitulo.AutoSize = true;
            this.lblSubtitulo.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lblSubtitulo.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.lblSubtitulo.Location = new System.Drawing.Point(50, 95);
            this.lblSubtitulo.MaximumSize = new System.Drawing.Size(400, 0);
            this.lblSubtitulo.Name = "lblSubtitulo";
            this.lblSubtitulo.Size = new System.Drawing.Size(286, 19);
            this.lblSubtitulo.TabIndex = 1;
            this.lblSubtitulo.Text = "Completa los datos para crear tu cuenta.";
            this.lblEmail.AutoSize = true;
            this.lblEmail.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblEmail.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.lblEmail.Location = new System.Drawing.Point(50, 135);
            this.lblEmail.Name = "lblEmail";
            this.lblEmail.Size = new System.Drawing.Size(140, 19);
            this.lblEmail.TabIndex = 2;
            this.lblEmail.Text = "Correo Electronico";
            this.pnlEmailInput.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(245)))));
            this.pnlEmailInput.Controls.Add(this.lblEmailIcon);
            this.pnlEmailInput.Controls.Add(this.txtEmail);
            this.pnlEmailInput.Location = new System.Drawing.Point(50, 160);
            this.pnlEmailInput.Name = "pnlEmailInput";
            this.pnlEmailInput.Size = new System.Drawing.Size(400, 45);
            this.pnlEmailInput.TabIndex = 3;
            this.lblEmailIcon.Font = new System.Drawing.Font("Segoe UI", 16F);
            this.lblEmailIcon.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(120)))), ((int)(((byte)(120)))));
            this.lblEmailIcon.Location = new System.Drawing.Point(10, 8);
            this.lblEmailIcon.Name = "lblEmailIcon";
            this.lblEmailIcon.Size = new System.Drawing.Size(30, 30);
            this.lblEmailIcon.TabIndex = 0;
            this.lblEmailIcon.Text = "";
            this.lblEmailIcon.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.txtEmail.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(245)))));
            this.txtEmail.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.txtEmail.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.txtEmail.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.txtEmail.Location = new System.Drawing.Point(50, 12);
            this.txtEmail.Name = "txtEmail";
            this.txtEmail.Size = new System.Drawing.Size(335, 22);
            this.txtEmail.TabIndex = 1;
            this.lblUser.AutoSize = true;
            this.lblUser.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblUser.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.lblUser.Location = new System.Drawing.Point(50, 220);
            this.lblUser.Name = "lblUser";
            this.lblUser.Size = new System.Drawing.Size(141, 19);
            this.lblUser.TabIndex = 4;
            this.lblUser.Text = "Nombre de Usuario";
            this.pnlUserInput.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(245)))));
            this.pnlUserInput.Controls.Add(this.lblUserIcon);
            this.pnlUserInput.Controls.Add(this.txtUser);
            this.pnlUserInput.Location = new System.Drawing.Point(50, 245);
            this.pnlUserInput.Name = "pnlUserInput";
            this.pnlUserInput.Size = new System.Drawing.Size(400, 45);
            this.pnlUserInput.TabIndex = 5;
            this.lblUserIcon.Font = new System.Drawing.Font("Segoe UI", 16F);
            this.lblUserIcon.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(120)))), ((int)(((byte)(120)))));
            this.lblUserIcon.Location = new System.Drawing.Point(10, 8);
            this.lblUserIcon.Name = "lblUserIcon";
            this.lblUserIcon.Size = new System.Drawing.Size(30, 30);
            this.lblUserIcon.TabIndex = 0;
            this.lblUserIcon.Text = "";
            this.lblUserIcon.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.txtUser.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(245)))));
            this.txtUser.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.txtUser.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.txtUser.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.txtUser.Location = new System.Drawing.Point(50, 12);
            this.txtUser.Name = "txtUser";
            this.txtUser.Size = new System.Drawing.Size(335, 22);
            this.txtUser.TabIndex = 1;
            this.lblPassword.AutoSize = true;
            this.lblPassword.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblPassword.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.lblPassword.Location = new System.Drawing.Point(50, 305);
            this.lblPassword.Name = "lblPassword";
            this.lblPassword.Size = new System.Drawing.Size(82, 19);
            this.lblPassword.TabIndex = 6;
            this.lblPassword.Text = "Contrasena";
            this.pnlPassInput.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(245)))));
            this.pnlPassInput.Controls.Add(this.lblPassIcon);
            this.pnlPassInput.Controls.Add(this.txtPass);
            this.pnlPassInput.Location = new System.Drawing.Point(50, 330);
            this.pnlPassInput.Name = "pnlPassInput";
            this.pnlPassInput.Size = new System.Drawing.Size(400, 45);
            this.pnlPassInput.TabIndex = 7;
            this.lblPassIcon.Font = new System.Drawing.Font("Segoe UI", 16F);
            this.lblPassIcon.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(120)))), ((int)(((byte)(120)))));
            this.lblPassIcon.Location = new System.Drawing.Point(10, 8);
            this.lblPassIcon.Name = "lblPassIcon";
            this.lblPassIcon.Size = new System.Drawing.Size(30, 30);
            this.lblPassIcon.TabIndex = 0;
            this.lblPassIcon.Text = "";
            this.lblPassIcon.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.txtPass.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(245)))));
            this.txtPass.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.txtPass.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.txtPass.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.txtPass.Location = new System.Drawing.Point(50, 12);
            this.txtPass.Name = "txtPass";
            this.txtPass.PasswordChar = '●';
            this.txtPass.Size = new System.Drawing.Size(335, 22);
            this.txtPass.TabIndex = 1;
            this.lblRequisitos.Font = new System.Drawing.Font("Segoe UI", 8.5F);
            this.lblRequisitos.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(120)))), ((int)(((byte)(120)))));
            this.lblRequisitos.Location = new System.Drawing.Point(50, 385);
            this.lblRequisitos.Name = "lblRequisitos";
            this.lblRequisitos.Size = new System.Drawing.Size(400, 30);
            this.lblRequisitos.TabIndex = 8;
            this.lblRequisitos.Text = "Minimo 8 caracteres, incluir mayusculas, minusculas y numeros.";
            this.lblRequisitos.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnRegister.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.BtnRegister.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnRegister.FlatAppearance.BorderSize = 0;
            this.BtnRegister.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.BtnRegister.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold);
            this.BtnRegister.ForeColor = System.Drawing.Color.White;
            this.BtnRegister.Location = new System.Drawing.Point(50, 425);
            this.BtnRegister.Name = "BtnRegister";
            this.BtnRegister.Size = new System.Drawing.Size(400, 45);
            this.BtnRegister.TabIndex = 9;
            this.BtnRegister.Text = "Crear Cuenta";
            this.BtnRegister.UseVisualStyleBackColor = false;
            this.BtnRegister.Click += new System.EventHandler(this.BtnRegister_Click);
            this.btnVolverLogin.BackColor = System.Drawing.Color.Transparent;
            this.btnVolverLogin.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnVolverLogin.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.btnVolverLogin.FlatAppearance.BorderSize = 2;
            this.btnVolverLogin.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnVolverLogin.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.btnVolverLogin.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.btnVolverLogin.Location = new System.Drawing.Point(50, 485);
            this.btnVolverLogin.Name = "btnVolverLogin";
            this.btnVolverLogin.Size = new System.Drawing.Size(400, 40);
            this.btnVolverLogin.TabIndex = 10;
            this.btnVolverLogin.Text = "a† Volver al Login";
            this.btnVolverLogin.UseVisualStyleBackColor = false;
            this.btnVolverLogin.Click += new System.EventHandler(this.btnVolverLogin_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(600, 650);
            this.Controls.Add(this.pnlMain);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Sizable;
            this.MinimumSize = new System.Drawing.Size(550, 600);
            this.Name = "Register";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Registrarse - TicketsPro";
            this.pnlMain.ResumeLayout(false);
            this.pnlContent.ResumeLayout(false);
            this.pnlContent.PerformLayout();
            this.pnlEmailInput.ResumeLayout(false);
            this.pnlEmailInput.PerformLayout();
            this.pnlUserInput.ResumeLayout(false);
            this.pnlUserInput.PerformLayout();
            this.pnlPassInput.ResumeLayout(false);
            this.pnlPassInput.PerformLayout();
            this.ResumeLayout(false);
        }
        #endregion
        private Panel pnlMain;
        private Panel pnlContent;
        private Label lblTitulo;
        private Label lblSubtitulo;
        private Label lblEmail;
        private Panel pnlEmailInput;
        private Label lblEmailIcon;
        private TextBox txtEmail;
        private Label lblUser;
        private Panel pnlUserInput;
        private Label lblUserIcon;
        private TextBox txtUser;
        private Label lblPassword;
        private Panel pnlPassInput;
        private Label lblPassIcon;
        private TextBox txtPass;
        private Label lblRequisitos;
        private Button BtnRegister;
        private Button btnVolverLogin;
    }
}
