namespace TicketPro
{
    partial class FormGestionAccesos
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.tabControlAccesos = new System.Windows.Forms.TabControl();
            this.tabUsuarios = new System.Windows.Forms.TabPage();
            this.button1 = new System.Windows.Forms.Button();
            this.btnGuardar = new System.Windows.Forms.Button();
            this.grpPatentesUsuario = new System.Windows.Forms.GroupBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.btnPatRem = new System.Windows.Forms.Button();
            this.btnPatAdd = new System.Windows.Forms.Button();
            this.lstPatAsig = new System.Windows.Forms.ListBox();
            this.lstPatDisp = new System.Windows.Forms.ListBox();
            this.grpFamiliasUsuario = new System.Windows.Forms.GroupBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.btnFamRem = new System.Windows.Forms.Button();
            this.btnFamAdd = new System.Windows.Forms.Button();
            this.lstFamAsig = new System.Windows.Forms.ListBox();
            this.lstFamDisp = new System.Windows.Forms.ListBox();
            this.cmbUsuarios = new System.Windows.Forms.ComboBox();
            this.label5 = new System.Windows.Forms.Label();
            this.tabFamilias = new System.Windows.Forms.TabPage();
            this.grpPatentesFamilia = new System.Windows.Forms.GroupBox();
            this.chkPatentesParaFamilia = new System.Windows.Forms.CheckedListBox();
            this.btnGuardarPatentesParaFamilia = new System.Windows.Forms.Button();
            this.grpGestionFamilias = new System.Windows.Forms.GroupBox();
            this.btnEliminarFamilia = new System.Windows.Forms.Button();
            this.btnNuevaFamilia = new System.Windows.Forms.Button();
            this.btnRenombrarFamilia = new System.Windows.Forms.Button();
            this.txtNuevoNombreFamilia = new System.Windows.Forms.TextBox();
            this.lstTodasFamilias = new System.Windows.Forms.ListBox();
            this.cmbFamilias = new System.Windows.Forms.ComboBox();
            this.label8 = new System.Windows.Forms.Label();
            this.tabPatentes = new System.Windows.Forms.TabPage();
            this.btnEliminarPatente = new System.Windows.Forms.Button();
            this.btnNuevaPatente = new System.Windows.Forms.Button();
            this.lstTodasPatentes = new System.Windows.Forms.ListBox();
            this.txtBuscarPatente = new System.Windows.Forms.TextBox();
            this.label11 = new System.Windows.Forms.Label();
            this.tabControlAccesos.SuspendLayout();
            this.tabUsuarios.SuspendLayout();
            this.grpPatentesUsuario.SuspendLayout();
            this.grpFamiliasUsuario.SuspendLayout();
            this.tabFamilias.SuspendLayout();
            this.grpPatentesFamilia.SuspendLayout();
            this.grpGestionFamilias.SuspendLayout();
            this.tabPatentes.SuspendLayout();
            this.SuspendLayout();
            this.tabControlAccesos.Controls.Add(this.tabUsuarios);
            this.tabControlAccesos.Controls.Add(this.tabFamilias);
            this.tabControlAccesos.Controls.Add(this.tabPatentes);
            this.tabControlAccesos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControlAccesos.DrawMode = System.Windows.Forms.TabDrawMode.OwnerDrawFixed;
            this.tabControlAccesos.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.tabControlAccesos.Location = new System.Drawing.Point(0, 0);
            this.tabControlAccesos.Name = "tabControlAccesos";
            this.tabControlAccesos.SelectedIndex = 0;
            this.tabControlAccesos.Size = new System.Drawing.Size(784, 561);
            this.tabControlAccesos.TabIndex = 3;
            this.tabUsuarios.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            this.tabUsuarios.Controls.Add(this.button1);
            this.tabUsuarios.Controls.Add(this.btnGuardar);
            this.tabUsuarios.Controls.Add(this.grpPatentesUsuario);
            this.tabUsuarios.Controls.Add(this.grpFamiliasUsuario);
            this.tabUsuarios.Controls.Add(this.cmbUsuarios);
            this.tabUsuarios.Controls.Add(this.label5);
            this.tabUsuarios.Location = new System.Drawing.Point(4, 24);
            this.tabUsuarios.Name = "tabUsuarios";
            this.tabUsuarios.Padding = new System.Windows.Forms.Padding(3);
            this.tabUsuarios.Size = new System.Drawing.Size(776, 533);
            this.tabUsuarios.TabIndex = 0;
            this.tabUsuarios.Text = "Usuarios";
            this.button1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.button1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(90)))));
            this.button1.FlatAppearance.BorderSize = 0;
            this.button1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button1.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.button1.ForeColor = System.Drawing.Color.White;
            this.button1.Location = new System.Drawing.Point(12, 484);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(138, 30);
            this.button1.TabIndex = 5;
            this.button1.Text = "Eliminar_Usuario";
            this.button1.UseVisualStyleBackColor = false;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            this.btnGuardar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnGuardar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(90)))));
            this.btnGuardar.FlatAppearance.BorderSize = 0;
            this.btnGuardar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnGuardar.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGuardar.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.Location = new System.Drawing.Point(624, 484);
            this.btnGuardar.Name = "btnGuardar";
            this.btnGuardar.Size = new System.Drawing.Size(138, 30);
            this.btnGuardar.TabIndex = 4;
            this.btnGuardar.Text = "Guardar_Cambios";
            this.btnGuardar.UseVisualStyleBackColor = false;
            this.btnGuardar.Click += new System.EventHandler(this.btnGuardar_Click_1);
            this.grpPatentesUsuario.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.grpPatentesUsuario.Controls.Add(this.label3);
            this.grpPatentesUsuario.Controls.Add(this.label4);
            this.grpPatentesUsuario.Controls.Add(this.btnPatRem);
            this.grpPatentesUsuario.Controls.Add(this.btnPatAdd);
            this.grpPatentesUsuario.Controls.Add(this.lstPatAsig);
            this.grpPatentesUsuario.Controls.Add(this.lstPatDisp);
            this.grpPatentesUsuario.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.grpPatentesUsuario.ForeColor = System.Drawing.Color.Gainsboro;
            this.grpPatentesUsuario.Location = new System.Drawing.Point(12, 269);
            this.grpPatentesUsuario.Name = "grpPatentesUsuario";
            this.grpPatentesUsuario.Size = new System.Drawing.Size(750, 196);
            this.grpPatentesUsuario.TabIndex = 3;
            this.grpPatentesUsuario.TabStop = false;
            this.grpPatentesUsuario.Text = "Patentes_del_usuario";
            this.label3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(411, 25);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(61, 15);
            this.label3.TabIndex = 5;
            this.label3.Text = "Asignadas";
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.label4.ForeColor = System.Drawing.Color.White;
            this.label4.Location = new System.Drawing.Point(15, 25);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(68, 15);
            this.label4.TabIndex = 4;
            this.label4.Text = "Disponibles";
            this.btnPatRem.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnPatRem.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(90)))));
            this.btnPatRem.FlatAppearance.BorderSize = 0;
            this.btnPatRem.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnPatRem.Font = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.btnPatRem.ForeColor = System.Drawing.Color.White;
            this.btnPatRem.Location = new System.Drawing.Point(341, 108);
            this.btnPatRem.Name = "btnPatRem";
            this.btnPatRem.Size = new System.Drawing.Size(64, 23);
            this.btnPatRem.TabIndex = 3;
            this.btnPatRem.Text = "<";
            this.btnPatRem.UseVisualStyleBackColor = false;
            this.btnPatAdd.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnPatAdd.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(90)))));
            this.btnPatAdd.FlatAppearance.BorderSize = 0;
            this.btnPatAdd.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnPatAdd.Font = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.btnPatAdd.ForeColor = System.Drawing.Color.White;
            this.btnPatAdd.Location = new System.Drawing.Point(341, 82);
            this.btnPatAdd.Name = "btnPatAdd";
            this.btnPatAdd.Size = new System.Drawing.Size(64, 20);
            this.btnPatAdd.TabIndex = 2;
            this.btnPatAdd.Text = ">";
            this.btnPatAdd.UseVisualStyleBackColor = false;
            this.btnPatAdd.Click += new System.EventHandler(this.btnPatAdd_Click);
            this.lstPatAsig.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lstPatAsig.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.lstPatAsig.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.lstPatAsig.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lstPatAsig.ForeColor = System.Drawing.Color.White;
            this.lstPatAsig.FormattingEnabled = true;
            this.lstPatAsig.ItemHeight = 15;
            this.lstPatAsig.Location = new System.Drawing.Point(411, 43);
            this.lstPatAsig.Name = "lstPatAsig";
            this.lstPatAsig.Size = new System.Drawing.Size(325, 135);
            this.lstPatAsig.TabIndex = 1;
            this.lstPatDisp.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.lstPatDisp.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.lstPatDisp.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.lstPatDisp.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lstPatDisp.ForeColor = System.Drawing.Color.White;
            this.lstPatDisp.FormattingEnabled = true;
            this.lstPatDisp.ItemHeight = 15;
            this.lstPatDisp.Location = new System.Drawing.Point(15, 43);
            this.lstPatDisp.Name = "lstPatDisp";
            this.lstPatDisp.Size = new System.Drawing.Size(325, 135);
            this.lstPatDisp.TabIndex = 0;
            this.grpFamiliasUsuario.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.grpFamiliasUsuario.Controls.Add(this.label2);
            this.grpFamiliasUsuario.Controls.Add(this.label1);
            this.grpFamiliasUsuario.Controls.Add(this.btnFamRem);
            this.grpFamiliasUsuario.Controls.Add(this.btnFamAdd);
            this.grpFamiliasUsuario.Controls.Add(this.lstFamAsig);
            this.grpFamiliasUsuario.Controls.Add(this.lstFamDisp);
            this.grpFamiliasUsuario.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.grpFamiliasUsuario.ForeColor = System.Drawing.Color.Gainsboro;
            this.grpFamiliasUsuario.Location = new System.Drawing.Point(12, 57);
            this.grpFamiliasUsuario.Name = "grpFamiliasUsuario";
            this.grpFamiliasUsuario.Size = new System.Drawing.Size(750, 196);
            this.grpFamiliasUsuario.TabIndex = 2;
            this.grpFamiliasUsuario.TabStop = false;
            this.grpFamiliasUsuario.Text = "Familias_del_usuario";
            this.label2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(411, 25);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(61, 15);
            this.label2.TabIndex = 5;
            this.label2.Text = "Asignadas";
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(15, 25);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(68, 15);
            this.label1.TabIndex = 4;
            this.label1.Text = "Disponibles";
            this.btnFamRem.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnFamRem.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(90)))));
            this.btnFamRem.FlatAppearance.BorderSize = 0;
            this.btnFamRem.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFamRem.Font = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.btnFamRem.ForeColor = System.Drawing.Color.White;
            this.btnFamRem.Location = new System.Drawing.Point(341, 123);
            this.btnFamRem.Name = "btnFamRem";
            this.btnFamRem.Size = new System.Drawing.Size(64, 22);
            this.btnFamRem.TabIndex = 3;
            this.btnFamRem.Text = "<";
            this.btnFamRem.UseVisualStyleBackColor = false;
            this.btnFamAdd.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnFamAdd.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(90)))));
            this.btnFamAdd.FlatAppearance.BorderSize = 0;
            this.btnFamAdd.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFamAdd.Font = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.btnFamAdd.ForeColor = System.Drawing.Color.White;
            this.btnFamAdd.Location = new System.Drawing.Point(341, 95);
            this.btnFamAdd.Name = "btnFamAdd";
            this.btnFamAdd.Size = new System.Drawing.Size(64, 22);
            this.btnFamAdd.TabIndex = 2;
            this.btnFamAdd.Text = ">";
            this.btnFamAdd.UseVisualStyleBackColor = false;
            this.lstFamAsig.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lstFamAsig.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.lstFamAsig.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.lstFamAsig.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lstFamAsig.ForeColor = System.Drawing.Color.White;
            this.lstFamAsig.FormattingEnabled = true;
            this.lstFamAsig.ItemHeight = 15;
            this.lstFamAsig.Location = new System.Drawing.Point(411, 43);
            this.lstFamAsig.Name = "lstFamAsig";
            this.lstFamAsig.Size = new System.Drawing.Size(325, 135);
            this.lstFamAsig.TabIndex = 1;
            this.lstFamDisp.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.lstFamDisp.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.lstFamDisp.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.lstFamDisp.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lstFamDisp.ForeColor = System.Drawing.Color.White;
            this.lstFamDisp.FormattingEnabled = true;
            this.lstFamDisp.ItemHeight = 15;
            this.lstFamDisp.Location = new System.Drawing.Point(15, 43);
            this.lstFamDisp.Name = "lstFamDisp";
            this.lstFamDisp.Size = new System.Drawing.Size(325, 135);
            this.lstFamDisp.TabIndex = 0;
            this.cmbUsuarios.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.cmbUsuarios.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbUsuarios.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbUsuarios.ForeColor = System.Drawing.Color.White;
            this.cmbUsuarios.FormattingEnabled = true;
            this.cmbUsuarios.Location = new System.Drawing.Point(145, 21);
            this.cmbUsuarios.Name = "cmbUsuarios";
            this.cmbUsuarios.Size = new System.Drawing.Size(393, 23);
            this.cmbUsuarios.TabIndex = 1;
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(18, 24);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(126, 15);
            this.label5.TabIndex = 0;
            this.label5.Text = "Seleccione_un_usuario";
            this.tabFamilias.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            this.tabFamilias.Controls.Add(this.grpPatentesFamilia);
            this.tabFamilias.Controls.Add(this.grpGestionFamilias);
            this.tabFamilias.Controls.Add(this.cmbFamilias);
            this.tabFamilias.Controls.Add(this.label8);
            this.tabFamilias.Location = new System.Drawing.Point(4, 24);
            this.tabFamilias.Name = "tabFamilias";
            this.tabFamilias.Padding = new System.Windows.Forms.Padding(3);
            this.tabFamilias.Size = new System.Drawing.Size(776, 533);
            this.tabFamilias.TabIndex = 1;
            this.tabFamilias.Text = "Familias";
            this.grpPatentesFamilia.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.grpPatentesFamilia.Controls.Add(this.chkPatentesParaFamilia);
            this.grpPatentesFamilia.Controls.Add(this.btnGuardarPatentesParaFamilia);
            this.grpPatentesFamilia.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.grpPatentesFamilia.ForeColor = System.Drawing.Color.Gainsboro;
            this.grpPatentesFamilia.Location = new System.Drawing.Point(12, 281);
            this.grpPatentesFamilia.Name = "grpPatentesFamilia";
            this.grpPatentesFamilia.Size = new System.Drawing.Size(750, 196);
            this.grpPatentesFamilia.TabIndex = 5;
            this.grpPatentesFamilia.TabStop = false;
            this.grpPatentesFamilia.Text = "Patentes_de_la_familia_seleccionada";
            this.chkPatentesParaFamilia.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.chkPatentesParaFamilia.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.chkPatentesParaFamilia.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.chkPatentesParaFamilia.CheckOnClick = true;
            this.chkPatentesParaFamilia.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.chkPatentesParaFamilia.ForeColor = System.Drawing.Color.White;
            this.chkPatentesParaFamilia.FormattingEnabled = true;
            this.chkPatentesParaFamilia.Location = new System.Drawing.Point(15, 25);
            this.chkPatentesParaFamilia.Name = "chkPatentesParaFamilia";
            this.chkPatentesParaFamilia.Size = new System.Drawing.Size(550, 144);
            this.chkPatentesParaFamilia.TabIndex = 0;
            this.btnGuardarPatentesParaFamilia.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnGuardarPatentesParaFamilia.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(90)))));
            this.btnGuardarPatentesParaFamilia.FlatAppearance.BorderSize = 0;
            this.btnGuardarPatentesParaFamilia.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnGuardarPatentesParaFamilia.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnGuardarPatentesParaFamilia.ForeColor = System.Drawing.Color.White;
            this.btnGuardarPatentesParaFamilia.Location = new System.Drawing.Point(580, 25);
            this.btnGuardarPatentesParaFamilia.Name = "btnGuardarPatentesParaFamilia";
            this.btnGuardarPatentesParaFamilia.Size = new System.Drawing.Size(150, 30);
            this.btnGuardarPatentesParaFamilia.TabIndex = 1;
            this.btnGuardarPatentesParaFamilia.Text = "Guardar_Patentes";
            this.btnGuardarPatentesParaFamilia.UseVisualStyleBackColor = false;
            this.grpGestionFamilias.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.grpGestionFamilias.Controls.Add(this.btnEliminarFamilia);
            this.grpGestionFamilias.Controls.Add(this.btnNuevaFamilia);
            this.grpGestionFamilias.Controls.Add(this.btnRenombrarFamilia);
            this.grpGestionFamilias.Controls.Add(this.txtNuevoNombreFamilia);
            this.grpGestionFamilias.Controls.Add(this.lstTodasFamilias);
            this.grpGestionFamilias.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.grpGestionFamilias.ForeColor = System.Drawing.Color.Gainsboro;
            this.grpGestionFamilias.Location = new System.Drawing.Point(12, 19);
            this.grpGestionFamilias.Name = "grpGestionFamilias";
            this.grpGestionFamilias.Size = new System.Drawing.Size(750, 196);
            this.grpGestionFamilias.TabIndex = 4;
            this.grpGestionFamilias.TabStop = false;
            this.grpGestionFamilias.Text = "Gestion_de_Familias";
            this.btnEliminarFamilia.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnEliminarFamilia.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(90)))));
            this.btnEliminarFamilia.FlatAppearance.BorderSize = 0;
            this.btnEliminarFamilia.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnEliminarFamilia.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnEliminarFamilia.ForeColor = System.Drawing.Color.White;
            this.btnEliminarFamilia.Location = new System.Drawing.Point(628, 79);
            this.btnEliminarFamilia.Name = "btnEliminarFamilia";
            this.btnEliminarFamilia.Size = new System.Drawing.Size(100, 30);
            this.btnEliminarFamilia.TabIndex = 2;
            this.btnEliminarFamilia.Text = "Eliminar";
            this.btnEliminarFamilia.UseVisualStyleBackColor = false;
            this.btnNuevaFamilia.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnNuevaFamilia.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(90)))));
            this.btnNuevaFamilia.FlatAppearance.BorderSize = 0;
            this.btnNuevaFamilia.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnNuevaFamilia.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnNuevaFamilia.ForeColor = System.Drawing.Color.White;
            this.btnNuevaFamilia.Location = new System.Drawing.Point(628, 43);
            this.btnNuevaFamilia.Name = "btnNuevaFamilia";
            this.btnNuevaFamilia.Size = new System.Drawing.Size(100, 30);
            this.btnNuevaFamilia.TabIndex = 1;
            this.btnNuevaFamilia.Text = "Nueva";
            this.btnNuevaFamilia.UseVisualStyleBackColor = false;
            this.btnRenombrarFamilia.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnRenombrarFamilia.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(90)))));
            this.btnRenombrarFamilia.FlatAppearance.BorderSize = 0;
            this.btnRenombrarFamilia.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnRenombrarFamilia.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnRenombrarFamilia.ForeColor = System.Drawing.Color.White;
            this.btnRenombrarFamilia.Location = new System.Drawing.Point(628, 115);
            this.btnRenombrarFamilia.Name = "btnRenombrarFamilia";
            this.btnRenombrarFamilia.Size = new System.Drawing.Size(100, 30);
            this.btnRenombrarFamilia.TabIndex = 4;
            this.btnRenombrarFamilia.Text = "Renombrar";
            this.btnRenombrarFamilia.UseVisualStyleBackColor = false;
            this.txtNuevoNombreFamilia.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.txtNuevoNombreFamilia.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.txtNuevoNombreFamilia.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtNuevoNombreFamilia.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtNuevoNombreFamilia.ForeColor = System.Drawing.Color.White;
            this.txtNuevoNombreFamilia.Location = new System.Drawing.Point(628, 115);
            this.txtNuevoNombreFamilia.Name = "txtNuevoNombreFamilia";
            this.txtNuevoNombreFamilia.Size = new System.Drawing.Size(100, 23);
            this.txtNuevoNombreFamilia.TabIndex = 3;
            this.txtNuevoNombreFamilia.Visible = false;
            this.lstTodasFamilias.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lstTodasFamilias.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.lstTodasFamilias.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.lstTodasFamilias.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lstTodasFamilias.ForeColor = System.Drawing.Color.White;
            this.lstTodasFamilias.FormattingEnabled = true;
            this.lstTodasFamilias.ItemHeight = 15;
            this.lstTodasFamilias.Location = new System.Drawing.Point(15, 43);
            this.lstTodasFamilias.Name = "lstTodasFamilias";
            this.lstTodasFamilias.Size = new System.Drawing.Size(607, 135);
            this.lstTodasFamilias.TabIndex = 0;
            this.cmbFamilias.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.cmbFamilias.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbFamilias.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbFamilias.ForeColor = System.Drawing.Color.White;
            this.cmbFamilias.FormattingEnabled = true;
            this.cmbFamilias.Location = new System.Drawing.Point(143, 236);
            this.cmbFamilias.Name = "cmbFamilias";
            this.cmbFamilias.Size = new System.Drawing.Size(393, 23);
            this.cmbFamilias.TabIndex = 3;
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(16, 239);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(129, 15);
            this.label8.TabIndex = 2;
            this.label8.Text = "Seleccione_una_familia";
            this.tabPatentes.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            this.tabPatentes.Controls.Add(this.btnEliminarPatente);
            this.tabPatentes.Controls.Add(this.btnNuevaPatente);
            this.tabPatentes.Controls.Add(this.lstTodasPatentes);
            this.tabPatentes.Controls.Add(this.txtBuscarPatente);
            this.tabPatentes.Controls.Add(this.label11);
            this.tabPatentes.Location = new System.Drawing.Point(4, 24);
            this.tabPatentes.Name = "tabPatentes";
            this.tabPatentes.Padding = new System.Windows.Forms.Padding(10);
            this.tabPatentes.Size = new System.Drawing.Size(776, 533);
            this.tabPatentes.TabIndex = 2;
            this.tabPatentes.Text = "Patentes";
            this.btnEliminarPatente.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnEliminarPatente.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(90)))));
            this.btnEliminarPatente.FlatAppearance.BorderSize = 0;
            this.btnEliminarPatente.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnEliminarPatente.ForeColor = System.Drawing.Color.White;
            this.btnEliminarPatente.Location = new System.Drawing.Point(643, 90);
            this.btnEliminarPatente.Name = "btnEliminarPatente";
            this.btnEliminarPatente.Size = new System.Drawing.Size(120, 30);
            this.btnEliminarPatente.TabIndex = 4;
            this.btnEliminarPatente.Text = "Eliminar_Patente";
            this.btnEliminarPatente.UseVisualStyleBackColor = false;
            this.btnNuevaPatente.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnNuevaPatente.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(90)))));
            this.btnNuevaPatente.FlatAppearance.BorderSize = 0;
            this.btnNuevaPatente.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnNuevaPatente.ForeColor = System.Drawing.Color.White;
            this.btnNuevaPatente.Location = new System.Drawing.Point(643, 54);
            this.btnNuevaPatente.Name = "btnNuevaPatente";
            this.btnNuevaPatente.Size = new System.Drawing.Size(120, 30);
            this.btnNuevaPatente.TabIndex = 3;
            this.btnNuevaPatente.Text = "Nueva_Patente";
            this.btnNuevaPatente.UseVisualStyleBackColor = false;
            this.lstTodasPatentes.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lstTodasPatentes.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.lstTodasPatentes.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.lstTodasPatentes.ForeColor = System.Drawing.Color.White;
            this.lstTodasPatentes.FormattingEnabled = true;
            this.lstTodasPatentes.ItemHeight = 15;
            this.lstTodasPatentes.Location = new System.Drawing.Point(13, 54);
            this.lstTodasPatentes.Name = "lstTodasPatentes";
            this.lstTodasPatentes.Size = new System.Drawing.Size(624, 450);
            this.lstTodasPatentes.TabIndex = 2;
            this.txtBuscarPatente.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtBuscarPatente.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.txtBuscarPatente.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtBuscarPatente.ForeColor = System.Drawing.Color.White;
            this.txtBuscarPatente.Location = new System.Drawing.Point(64, 13);
            this.txtBuscarPatente.Name = "txtBuscarPatente";
            this.txtBuscarPatente.Size = new System.Drawing.Size(573, 23);
            this.txtBuscarPatente.TabIndex = 1;
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(15, 16);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(75, 15);
            this.label11.TabIndex = 0;
            this.label11.Text = "Buscar_Label";
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            this.ClientSize = new System.Drawing.Size(784, 561);
            this.Controls.Add(this.tabControlAccesos);
            this.ForeColor = System.Drawing.Color.White;
            this.MinimumSize = new System.Drawing.Size(800, 600);
            this.Name = "FormGestionAccesos";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Gestion_de_Accesos";
            this.tabControlAccesos.ResumeLayout(false);
            this.tabUsuarios.ResumeLayout(false);
            this.tabUsuarios.PerformLayout();
            this.grpPatentesUsuario.ResumeLayout(false);
            this.grpPatentesUsuario.PerformLayout();
            this.grpFamiliasUsuario.ResumeLayout(false);
            this.grpFamiliasUsuario.PerformLayout();
            this.tabFamilias.ResumeLayout(false);
            this.tabFamilias.PerformLayout();
            this.grpPatentesFamilia.ResumeLayout(false);
            this.grpGestionFamilias.ResumeLayout(false);
            this.grpGestionFamilias.PerformLayout();
            this.tabPatentes.ResumeLayout(false);
            this.tabPatentes.PerformLayout();
            this.ResumeLayout(false);
        }
        #endregion
        private System.Windows.Forms.TabControl tabControlAccesos;
        private System.Windows.Forms.TabPage tabUsuarios;
        private System.Windows.Forms.Button btnGuardar;
        private System.Windows.Forms.GroupBox grpPatentesUsuario;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Button btnPatRem;
        private System.Windows.Forms.Button btnPatAdd;
        private System.Windows.Forms.ListBox lstPatAsig;
        private System.Windows.Forms.ListBox lstPatDisp;
        private System.Windows.Forms.GroupBox grpFamiliasUsuario;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Button btnFamRem;
        private System.Windows.Forms.Button btnFamAdd;
        private System.Windows.Forms.ListBox lstFamAsig;
        private System.Windows.Forms.ListBox lstFamDisp;
        private System.Windows.Forms.ComboBox cmbUsuarios;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TabPage tabFamilias;
        private System.Windows.Forms.GroupBox grpPatentesFamilia;
        private System.Windows.Forms.CheckedListBox chkPatentesParaFamilia;
        private System.Windows.Forms.Button btnGuardarPatentesParaFamilia;
        private System.Windows.Forms.TextBox txtNuevoNombreFamilia;
        private System.Windows.Forms.Button btnRenombrarFamilia;
        private System.Windows.Forms.GroupBox grpGestionFamilias;
        private System.Windows.Forms.Button btnEliminarFamilia;
        private System.Windows.Forms.Button btnNuevaFamilia;
        private System.Windows.Forms.ListBox lstTodasFamilias;
        private System.Windows.Forms.ComboBox cmbFamilias;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TabPage tabPatentes;
        private System.Windows.Forms.Button btnEliminarPatente;
        private System.Windows.Forms.Button btnNuevaPatente;
        private System.Windows.Forms.ListBox lstTodasPatentes;
        private System.Windows.Forms.TextBox txtBuscarPatente;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Button button1;
    }
}
