namespace TicketPro.Tecnico
{
    partial class VistaBitacora
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.pnlBody = new System.Windows.Forms.Panel();
            this.dgvBitacora = new System.Windows.Forms.DataGridView();
            this.pnlFiltros = new System.Windows.Forms.Panel();
            this.tblFiltros = new System.Windows.Forms.TableLayoutPanel();
            this.lblUsuario = new System.Windows.Forms.Label();
            this.txtUsuario = new System.Windows.Forms.TextBox();
            this.lblNivel = new System.Windows.Forms.Label();
            this.cboNivel = new System.Windows.Forms.ComboBox();
            this.lblAccion = new System.Windows.Forms.Label();
            this.txtAccion = new System.Windows.Forms.TextBox();
            this.lblDesde = new System.Windows.Forms.Label();
            this.dtpDesde = new System.Windows.Forms.DateTimePicker();
            this.lblHasta = new System.Windows.Forms.Label();
            this.dtpHasta = new System.Windows.Forms.DateTimePicker();
            this.pnlBotones = new System.Windows.Forms.Panel();
            this.btnLimpiar = new System.Windows.Forms.Button();
            this.pnlFooter = new System.Windows.Forms.Panel();
            this.lblContador = new System.Windows.Forms.Label();
            this.pnlBody.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvBitacora)).BeginInit();
            this.pnlFiltros.SuspendLayout();
            this.tblFiltros.SuspendLayout();
            this.pnlBotones.SuspendLayout();
            this.pnlFooter.SuspendLayout();
            this.SuspendLayout();
            this.pnlBody.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.pnlBody.Controls.Add(this.dgvBitacora);
            this.pnlBody.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlBody.Location = new System.Drawing.Point(0, 129);
            this.pnlBody.Name = "pnlBody";
            this.pnlBody.Padding = new System.Windows.Forms.Padding(15);
            this.pnlBody.Size = new System.Drawing.Size(1200, 521);
            this.pnlBody.TabIndex = 1;
            this.dgvBitacora.AllowUserToAddRows = false;
            this.dgvBitacora.AllowUserToDeleteRows = false;
            this.dgvBitacora.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvBitacora.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            this.dgvBitacora.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvBitacora.ColumnHeadersHeight = 50;
            this.dgvBitacora.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvBitacora.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvBitacora.EnableHeadersVisualStyles = false;
            this.dgvBitacora.Location = new System.Drawing.Point(15, 15);
            this.dgvBitacora.MultiSelect = false;
            this.dgvBitacora.Name = "dgvBitacora";
            this.dgvBitacora.ReadOnly = true;
            this.dgvBitacora.RowHeadersVisible = false;
            this.dgvBitacora.RowTemplate.Height = 35;
            this.dgvBitacora.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvBitacora.Size = new System.Drawing.Size(1170, 491);
            this.dgvBitacora.TabIndex = 0;
            this.pnlFiltros.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            this.pnlFiltros.Controls.Add(this.tblFiltros);
            this.pnlFiltros.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlFiltros.Location = new System.Drawing.Point(0, 0);
            this.pnlFiltros.Name = "pnlFiltros";
            this.pnlFiltros.Padding = new System.Windows.Forms.Padding(15, 10, 15, 10);
            this.pnlFiltros.Size = new System.Drawing.Size(1200, 129);
            this.pnlFiltros.TabIndex = 2;
            this.pnlFiltros.Paint += new System.Windows.Forms.PaintEventHandler(this.pnlFiltros_Paint);
            this.tblFiltros.ColumnCount = 6;
            this.tblFiltros.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tblFiltros.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.tblFiltros.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tblFiltros.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.tblFiltros.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.tblFiltros.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.tblFiltros.Controls.Add(this.lblUsuario, 0, 0);
            this.tblFiltros.Controls.Add(this.txtUsuario, 0, 1);
            this.tblFiltros.Controls.Add(this.lblNivel, 1, 0);
            this.tblFiltros.Controls.Add(this.cboNivel, 1, 1);
            this.tblFiltros.Controls.Add(this.lblAccion, 2, 0);
            this.tblFiltros.Controls.Add(this.txtAccion, 2, 1);
            this.tblFiltros.Controls.Add(this.lblDesde, 3, 0);
            this.tblFiltros.Controls.Add(this.dtpDesde, 3, 1);
            this.tblFiltros.Controls.Add(this.lblHasta, 4, 0);
            this.tblFiltros.Controls.Add(this.dtpHasta, 4, 1);
            this.tblFiltros.Controls.Add(this.pnlBotones, 5, 0);
            this.tblFiltros.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tblFiltros.Location = new System.Drawing.Point(15, 10);
            this.tblFiltros.Name = "tblFiltros";
            this.tblFiltros.RowCount = 2;
            this.tblFiltros.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
            this.tblFiltros.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tblFiltros.Size = new System.Drawing.Size(1170, 109);
            this.tblFiltros.TabIndex = 0;
            this.lblUsuario.AutoSize = true;
            this.lblUsuario.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblUsuario.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblUsuario.ForeColor = System.Drawing.Color.White;
            this.lblUsuario.Location = new System.Drawing.Point(3, 0);
            this.lblUsuario.Name = "lblUsuario";
            this.lblUsuario.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.lblUsuario.Size = new System.Drawing.Size(228, 25);
            this.lblUsuario.TabIndex = 0;
            this.lblUsuario.Text = " Usuario";
            this.lblUsuario.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.txtUsuario.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(65)))), ((int)(((byte)(80)))));
            this.txtUsuario.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtUsuario.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtUsuario.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtUsuario.ForeColor = System.Drawing.Color.White;
            this.txtUsuario.Location = new System.Drawing.Point(5, 30);
            this.txtUsuario.Margin = new System.Windows.Forms.Padding(5);
            this.txtUsuario.Name = "txtUsuario";
            this.txtUsuario.Size = new System.Drawing.Size(224, 25);
            this.txtUsuario.TabIndex = 1;
            this.lblNivel.AutoSize = true;
            this.lblNivel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblNivel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblNivel.ForeColor = System.Drawing.Color.White;
            this.lblNivel.Location = new System.Drawing.Point(237, 0);
            this.lblNivel.Name = "lblNivel";
            this.lblNivel.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.lblNivel.Size = new System.Drawing.Size(169, 25);
            this.lblNivel.TabIndex = 2;
            this.lblNivel.Text = "Nivel";
            this.lblNivel.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.cboNivel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(65)))), ((int)(((byte)(80)))));
            this.cboNivel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cboNivel.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboNivel.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboNivel.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cboNivel.ForeColor = System.Drawing.Color.White;
            this.cboNivel.FormattingEnabled = true;
            this.cboNivel.Location = new System.Drawing.Point(239, 30);
            this.cboNivel.Margin = new System.Windows.Forms.Padding(5);
            this.cboNivel.Name = "cboNivel";
            this.cboNivel.Size = new System.Drawing.Size(165, 25);
            this.cboNivel.TabIndex = 3;
            this.lblAccion.AutoSize = true;
            this.lblAccion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblAccion.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblAccion.ForeColor = System.Drawing.Color.White;
            this.lblAccion.Location = new System.Drawing.Point(412, 0);
            this.lblAccion.Name = "lblAccion";
            this.lblAccion.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.lblAccion.Size = new System.Drawing.Size(228, 25);
            this.lblAccion.TabIndex = 4;
            this.lblAccion.Text = "accion";
            this.lblAccion.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.txtAccion.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(65)))), ((int)(((byte)(80)))));
            this.txtAccion.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtAccion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtAccion.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtAccion.ForeColor = System.Drawing.Color.White;
            this.txtAccion.Location = new System.Drawing.Point(414, 30);
            this.txtAccion.Margin = new System.Windows.Forms.Padding(5);
            this.txtAccion.Name = "txtAccion";
            this.txtAccion.Size = new System.Drawing.Size(224, 25);
            this.txtAccion.TabIndex = 5;
            this.lblDesde.AutoSize = true;
            this.lblDesde.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDesde.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblDesde.ForeColor = System.Drawing.Color.White;
            this.lblDesde.Location = new System.Drawing.Point(646, 0);
            this.lblDesde.Name = "lblDesde";
            this.lblDesde.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.lblDesde.Size = new System.Drawing.Size(169, 25);
            this.lblDesde.TabIndex = 6;
            this.lblDesde.Text = "Desde";
            this.lblDesde.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.dtpDesde.CalendarMonthBackground = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(65)))), ((int)(((byte)(80)))));
            this.dtpDesde.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dtpDesde.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.dtpDesde.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtpDesde.Location = new System.Drawing.Point(648, 30);
            this.dtpDesde.Margin = new System.Windows.Forms.Padding(5);
            this.dtpDesde.Name = "dtpDesde";
            this.dtpDesde.Size = new System.Drawing.Size(165, 25);
            this.dtpDesde.TabIndex = 7;
            this.lblHasta.AutoSize = true;
            this.lblHasta.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHasta.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblHasta.ForeColor = System.Drawing.Color.White;
            this.lblHasta.Location = new System.Drawing.Point(821, 0);
            this.lblHasta.Name = "lblHasta";
            this.lblHasta.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.lblHasta.Size = new System.Drawing.Size(169, 25);
            this.lblHasta.TabIndex = 8;
            this.lblHasta.Text = "Hasta";
            this.lblHasta.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.dtpHasta.CalendarMonthBackground = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(65)))), ((int)(((byte)(80)))));
            this.dtpHasta.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dtpHasta.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.dtpHasta.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtpHasta.Location = new System.Drawing.Point(823, 30);
            this.dtpHasta.Margin = new System.Windows.Forms.Padding(5);
            this.dtpHasta.Name = "dtpHasta";
            this.dtpHasta.Size = new System.Drawing.Size(165, 25);
            this.dtpHasta.TabIndex = 9;
            this.pnlBotones.Controls.Add(this.btnLimpiar);
            this.pnlBotones.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlBotones.Location = new System.Drawing.Point(993, 0);
            this.pnlBotones.Margin = new System.Windows.Forms.Padding(0);
            this.pnlBotones.Name = "pnlBotones";
            this.tblFiltros.SetRowSpan(this.pnlBotones, 2);
            this.pnlBotones.Size = new System.Drawing.Size(177, 109);
            this.pnlBotones.TabIndex = 10;
            this.btnLimpiar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(90)))));
            this.btnLimpiar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnLimpiar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnLimpiar.FlatAppearance.BorderSize = 0;
            this.btnLimpiar.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(70)))));
            this.btnLimpiar.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(85)))), ((int)(((byte)(105)))));
            this.btnLimpiar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnLimpiar.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.btnLimpiar.ForeColor = System.Drawing.Color.White;
            this.btnLimpiar.Location = new System.Drawing.Point(0, 0);
            this.btnLimpiar.Margin = new System.Windows.Forms.Padding(5);
            this.btnLimpiar.Name = "btnLimpiar";
            this.btnLimpiar.Size = new System.Drawing.Size(177, 109);
            this.btnLimpiar.TabIndex = 1;
            this.btnLimpiar.Text = "Limpiar Filtros";
            this.btnLimpiar.UseVisualStyleBackColor = false;
            this.btnLimpiar.Click += new System.EventHandler(this.btnLimpiar_Click);
            this.pnlFooter.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            this.pnlFooter.Controls.Add(this.lblContador);
            this.pnlFooter.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.pnlFooter.Location = new System.Drawing.Point(0, 650);
            this.pnlFooter.Name = "pnlFooter";
            this.pnlFooter.Size = new System.Drawing.Size(1200, 40);
            this.pnlFooter.TabIndex = 3;
            this.lblContador.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblContador.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblContador.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(220)))));
            this.lblContador.Location = new System.Drawing.Point(0, 0);
            this.lblContador.Name = "lblContador";
            this.lblContador.Padding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.lblContador.Size = new System.Drawing.Size(1200, 40);
            this.lblContador.TabIndex = 0;
            this.lblContador.Text = "Total de registros: 0";
            this.lblContador.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.ClientSize = new System.Drawing.Size(1200, 690);
            this.Controls.Add(this.pnlBody);
            this.Controls.Add(this.pnlFiltros);
            this.Controls.Add(this.pnlFooter);
            this.MinimumSize = new System.Drawing.Size(1000, 600);
            this.Name = "VistaBitacora";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.pnlBody.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvBitacora)).EndInit();
            this.pnlFiltros.ResumeLayout(false);
            this.tblFiltros.ResumeLayout(false);
            this.tblFiltros.PerformLayout();
            this.pnlBotones.ResumeLayout(false);
            this.pnlFooter.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        private System.Windows.Forms.Panel pnlBody;
        private System.Windows.Forms.DataGridView dgvBitacora;
        private System.Windows.Forms.Panel pnlFiltros;
        private System.Windows.Forms.TableLayoutPanel tblFiltros;
        private System.Windows.Forms.Label lblUsuario;
        private System.Windows.Forms.TextBox txtUsuario;
        private System.Windows.Forms.Label lblNivel;
        private System.Windows.Forms.ComboBox cboNivel;
        private System.Windows.Forms.Label lblAccion;
        private System.Windows.Forms.TextBox txtAccion;
        private System.Windows.Forms.Label lblDesde;
        private System.Windows.Forms.DateTimePicker dtpDesde;
        private System.Windows.Forms.Label lblHasta;
        private System.Windows.Forms.DateTimePicker dtpHasta;
        private System.Windows.Forms.Panel pnlBotones;
        private System.Windows.Forms.Button btnLimpiar;
        private System.Windows.Forms.Panel pnlFooter;
        private System.Windows.Forms.Label lblContador;
    }
}
