namespace TicketPro.Tecnico
{
    partial class VistaAnaliticas
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Label lblFechaInicio;
        private System.Windows.Forms.DateTimePicker dtpFechaInicio;
        private System.Windows.Forms.Label lblFechaFin;
        private System.Windows.Forms.DateTimePicker dtpFechaFin;
        private System.Windows.Forms.Button btnAplicarFiltros;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanelCharts;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartTicketsEstado;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartTicketsTecnico;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartTendencia;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartTiempoSolucion;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartCumplimientoSLA;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea1 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Legend legend1 = new System.Windows.Forms.DataVisualization.Charting.Legend();
            System.Windows.Forms.DataVisualization.Charting.Series series1 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Title title1 = new System.Windows.Forms.DataVisualization.Charting.Title();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea2 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Legend legend2 = new System.Windows.Forms.DataVisualization.Charting.Legend();
            System.Windows.Forms.DataVisualization.Charting.Series series2 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Title title2 = new System.Windows.Forms.DataVisualization.Charting.Title();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea3 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Legend legend3 = new System.Windows.Forms.DataVisualization.Charting.Legend();
            System.Windows.Forms.DataVisualization.Charting.Series series3 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Title title3 = new System.Windows.Forms.DataVisualization.Charting.Title();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea4 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Legend legend4 = new System.Windows.Forms.DataVisualization.Charting.Legend();
            System.Windows.Forms.DataVisualization.Charting.Series series4 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Title title4 = new System.Windows.Forms.DataVisualization.Charting.Title();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea5 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Legend legend5 = new System.Windows.Forms.DataVisualization.Charting.Legend();
            System.Windows.Forms.DataVisualization.Charting.Series series5 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Title title5 = new System.Windows.Forms.DataVisualization.Charting.Title();
            this.btnAplicarFiltros = new System.Windows.Forms.Button();
            this.dtpFechaFin = new System.Windows.Forms.DateTimePicker();
            this.lblFechaFin = new System.Windows.Forms.Label();
            this.dtpFechaInicio = new System.Windows.Forms.DateTimePicker();
            this.lblFechaInicio = new System.Windows.Forms.Label();
            this.tableLayoutPanelCharts = new System.Windows.Forms.TableLayoutPanel();
            this.chartTicketsEstado = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.chartTicketsTecnico = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.chartTendencia = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.chartTiempoSolucion = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.chartCumplimientoSLA = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.tableLayoutPanelCharts.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.chartTicketsEstado)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartTicketsTecnico)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartTendencia)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartTiempoSolucion)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartCumplimientoSLA)).BeginInit();
            this.SuspendLayout();
            this.btnAplicarFiltros.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAplicarFiltros.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAplicarFiltros.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.btnAplicarFiltros.ForeColor = System.Drawing.Color.White;
            this.btnAplicarFiltros.Location = new System.Drawing.Point(747, 12);
            this.btnAplicarFiltros.Name = "btnAplicarFiltros";
            this.btnAplicarFiltros.Size = new System.Drawing.Size(110, 27);
            this.btnAplicarFiltros.TabIndex = 6;
            this.btnAplicarFiltros.Text = "Aplicar Filtros"; 
            this.btnAplicarFiltros.UseVisualStyleBackColor = true;
            this.dtpFechaFin.CustomFormat = "dd/MM/yyyy";
            this.dtpFechaFin.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtpFechaFin.Location = new System.Drawing.Point(540, 15);
            this.dtpFechaFin.Name = "dtpFechaFin";
            this.dtpFechaFin.Size = new System.Drawing.Size(120, 20);
            this.dtpFechaFin.TabIndex = 5;
            this.lblFechaFin.AutoSize = true;
            this.lblFechaFin.ForeColor = System.Drawing.Color.Gainsboro;
            this.lblFechaFin.Location = new System.Drawing.Point(480, 19);
            this.lblFechaFin.Name = "lblFechaFin";
            this.lblFechaFin.Size = new System.Drawing.Size(54, 13);
            this.lblFechaFin.TabIndex = 4;
            this.lblFechaFin.Text = "Fecha Fin:"; 
            this.dtpFechaInicio.CustomFormat = "dd/MM/yyyy";
            this.dtpFechaInicio.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtpFechaInicio.Location = new System.Drawing.Point(350, 15);
            this.dtpFechaInicio.Name = "dtpFechaInicio";
            this.dtpFechaInicio.Size = new System.Drawing.Size(120, 20);
            this.dtpFechaInicio.TabIndex = 3;
            this.lblFechaInicio.AutoSize = true;
            this.lblFechaInicio.ForeColor = System.Drawing.Color.Gainsboro;
            this.lblFechaInicio.Location = new System.Drawing.Point(277, 19);
            this.lblFechaInicio.Name = "lblFechaInicio";
            this.lblFechaInicio.Size = new System.Drawing.Size(67, 13);
            this.lblFechaInicio.TabIndex = 2;
            this.lblFechaInicio.Text = "Fecha Inicio:"; 
            this.tableLayoutPanelCharts.ColumnCount = 2;
            this.tableLayoutPanelCharts.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanelCharts.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanelCharts.Controls.Add(this.chartTicketsEstado, 0, 0);
            this.tableLayoutPanelCharts.Controls.Add(this.chartTicketsTecnico, 1, 0);
            this.tableLayoutPanelCharts.Controls.Add(this.chartTiempoSolucion, 0, 1);
            this.tableLayoutPanelCharts.Controls.Add(this.chartTendencia, 1, 1);
            this.tableLayoutPanelCharts.Controls.Add(this.chartCumplimientoSLA, 0, 2);
            this.tableLayoutPanelCharts.SetColumnSpan(this.chartCumplimientoSLA, 2);
            this.tableLayoutPanelCharts.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanelCharts.Location = new System.Drawing.Point(0, 50);
            this.tableLayoutPanelCharts.Name = "tableLayoutPanelCharts";
            this.tableLayoutPanelCharts.Padding = new System.Windows.Forms.Padding(10);
            this.tableLayoutPanelCharts.RowCount = 3;
            this.tableLayoutPanelCharts.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 35F));
            this.tableLayoutPanelCharts.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 35F));
            this.tableLayoutPanelCharts.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.tableLayoutPanelCharts.Size = new System.Drawing.Size(867, 550);
            this.tableLayoutPanelCharts.TabIndex = 1;
            this.chartTicketsEstado.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            chartArea1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            chartArea1.Name = "ChartArea1";
            this.chartTicketsEstado.ChartAreas.Add(chartArea1);
            this.chartTicketsEstado.Dock = System.Windows.Forms.DockStyle.Fill;
            legend1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            legend1.ForeColor = System.Drawing.Color.White;
            legend1.Name = "Legend1";
            this.chartTicketsEstado.Legends.Add(legend1);
            this.chartTicketsEstado.Location = new System.Drawing.Point(13, 13);
            this.chartTicketsEstado.Name = "chartTicketsEstado";
            series1.ChartArea = "ChartArea1";
            series1.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Doughnut;
            series1.Legend = "Legend1";
            series1.Name = "TicketsPorEstado";
            this.chartTicketsEstado.Series.Add(series1);
            this.chartTicketsEstado.Size = new System.Drawing.Size(417, 184);
            this.chartTicketsEstado.TabIndex = 0;
            this.chartTicketsEstado.Text = "Tickets por Estado";
            title1.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            title1.ForeColor = System.Drawing.Color.White;
            title1.Name = "TitleTicketsEstado";
            title1.Text = "Distribucion de Tickets por Estado"; 
            this.chartTicketsEstado.Titles.Add(title1);
            this.chartTicketsTecnico.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            chartArea2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            chartArea2.AxisX.LabelStyle.ForeColor = System.Drawing.Color.Silver;
            chartArea2.AxisX.LineColor = System.Drawing.Color.Gray;
            chartArea2.AxisY.LabelStyle.ForeColor = System.Drawing.Color.Silver;
            chartArea2.AxisY.LineColor = System.Drawing.Color.Gray;
            chartArea2.Name = "ChartArea1";
            this.chartTicketsTecnico.ChartAreas.Add(chartArea2);
            this.chartTicketsTecnico.Dock = System.Windows.Forms.DockStyle.Fill;
            legend2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            legend2.ForeColor = System.Drawing.Color.White;
            legend2.Name = "Legend1";
            this.chartTicketsTecnico.Legends.Add(legend2);
            this.chartTicketsTecnico.Location = new System.Drawing.Point(436, 13);
            this.chartTicketsTecnico.Name = "chartTicketsTecnico";
            series2.ChartArea = "ChartArea1";
            series2.Legend = "Legend1";
            series2.Name = "TicketsPorTecnico";
            this.chartTicketsTecnico.Series.Add(series2);
            this.chartTicketsTecnico.Size = new System.Drawing.Size(418, 184);
            this.chartTicketsTecnico.TabIndex = 1;
            this.chartTicketsTecnico.Text = "Tickets por Tecnico";
            title2.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            title2.ForeColor = System.Drawing.Color.White;
            title2.Name = "TitleTicketsTecnico";
            title2.Text = "Tickets Resueltos por Tecnico (Ultimos 30 dias)"; 
            this.chartTicketsTecnico.Titles.Add(title2);
            this.chartTendencia.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            chartArea3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            chartArea3.AxisX.LabelStyle.ForeColor = System.Drawing.Color.Silver;
            chartArea3.AxisX.LineColor = System.Drawing.Color.Gray;
            chartArea3.AxisY.LabelStyle.ForeColor = System.Drawing.Color.Silver;
            chartArea3.AxisY.LineColor = System.Drawing.Color.Gray;
            chartArea3.Name = "ChartArea1";
            this.chartTendencia.ChartAreas.Add(chartArea3);
            this.chartTendencia.Dock = System.Windows.Forms.DockStyle.Fill;
            legend3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            legend3.ForeColor = System.Drawing.Color.White;
            legend3.Name = "Legend1";
            this.chartTendencia.Legends.Add(legend3);
            this.chartTendencia.Location = new System.Drawing.Point(436, 203); 
            this.chartTendencia.Name = "chartTendencia";
            series3.ChartArea = "ChartArea1";
            series3.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series3.Legend = "Legend1";
            series3.Name = "TicketsCreados";
            this.chartTendencia.Series.Add(series3);
            this.chartTendencia.Size = new System.Drawing.Size(418, 184); 
            this.chartTendencia.TabIndex = 2;
            this.chartTendencia.Text = "Tendencia de Tickets";
            title3.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            title3.ForeColor = System.Drawing.Color.White;
            title3.Name = "TitleTendencia";
            title3.Text = "Tickets Creados vs Resueltos (Tendencia)"; 
            this.chartTendencia.Titles.Add(title3);
            this.chartTiempoSolucion.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            chartArea4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            chartArea4.AxisX.LabelStyle.ForeColor = System.Drawing.Color.Silver;
            chartArea4.AxisX.LineColor = System.Drawing.Color.Gray;
            chartArea4.AxisY.LabelStyle.ForeColor = System.Drawing.Color.Silver;
            chartArea4.AxisY.LineColor = System.Drawing.Color.Gray;
            chartArea4.Name = "ChartArea1";
            this.chartTiempoSolucion.ChartAreas.Add(chartArea4);
            this.chartTiempoSolucion.Dock = System.Windows.Forms.DockStyle.Fill;
            legend4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            legend4.ForeColor = System.Drawing.Color.White;
            legend4.Name = "Legend1";
            this.chartTiempoSolucion.Legends.Add(legend4);
            this.chartTiempoSolucion.Location = new System.Drawing.Point(13, 203);
            this.chartTiempoSolucion.Name = "chartTiempoSolucion";
            series4.ChartArea = "ChartArea1";
            series4.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Column; 
            series4.Legend = "Legend1";
            series4.Name = "TiempoPromedio";
            this.chartTiempoSolucion.Series.Add(series4);
            this.chartTiempoSolucion.Size = new System.Drawing.Size(417, 184);
            this.chartTiempoSolucion.TabIndex = 3;
            this.chartTiempoSolucion.Text = "Tiempo Promedio de solucion";
            title4.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            title4.ForeColor = System.Drawing.Color.White;
            title4.Name = "TitleTiempoSolucion";
            title4.Text = "Tiempo Promedio de solucion (en minutos)"; 
            this.chartTiempoSolucion.Titles.Add(title4);
            this.chartCumplimientoSLA.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            chartArea5.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            chartArea5.Name = "ChartArea1";
            this.chartCumplimientoSLA.ChartAreas.Add(chartArea5);
            this.chartCumplimientoSLA.Dock = System.Windows.Forms.DockStyle.Fill;
            legend5.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            legend5.ForeColor = System.Drawing.Color.White;
            legend5.Name = "Legend1";
            this.chartCumplimientoSLA.Legends.Add(legend5);
            this.chartCumplimientoSLA.Location = new System.Drawing.Point(13, 393);
            this.chartCumplimientoSLA.Name = "chartCumplimientoSLA";
            series5.ChartArea = "ChartArea1";
            series5.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Doughnut;
            series5.Legend = "Legend1";
            series5.Name = "CumplimientoSLA";
            this.chartCumplimientoSLA.Series.Add(series5);
            this.chartCumplimientoSLA.Size = new System.Drawing.Size(841, 144);
            this.chartCumplimientoSLA.TabIndex = 4;
            this.chartCumplimientoSLA.Text = "Cumplimiento SLA";
            title5.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            title5.ForeColor = System.Drawing.Color.White;
            title5.Name = "TitleCumplimientoSLA";
            title5.Text = "Cumplimiento de SLA";
            this.chartCumplimientoSLA.Titles.Add(title5);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            this.ClientSize = new System.Drawing.Size(867, 600);
            this.Controls.Add(this.tableLayoutPanelCharts);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Sizable;
            this.Name = "VistaAnaliticas";
            this.Text = "VistaAnaliticas";
            this.tableLayoutPanelCharts.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.chartTicketsEstado)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartTicketsTecnico)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartTendencia)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartTiempoSolucion)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartCumplimientoSLA)).EndInit();
            this.ResumeLayout(false);
        }
        #endregion
    }
}
