namespace TicketPro
{
    partial class VistaMainForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(VistaMainForm));
            this.panelMenu = new System.Windows.Forms.Panel();
            this.btnBackup = new System.Windows.Forms.Button();
            this.btnAnaliticas = new System.Windows.Forms.Button();
            this.btnBitacora = new System.Windows.Forms.Button();
            this.btnGestionMaestros = new System.Windows.Forms.Button();
            this.btnGestionInventario = new System.Windows.Forms.Button();
            this.btnCerrarSesion = new System.Windows.Forms.Button();
            this.btnGestionAccesos = new System.Windows.Forms.Button();
            this.btnCrearTicket = new System.Windows.Forms.Button();
            this.btnCasos = new System.Windows.Forms.Button();
            this.panelTitulo = new System.Windows.Forms.Panel();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.lblSubtitulo = new System.Windows.Forms.Label();
            this.panelContenido = new System.Windows.Forms.Panel();
            this.flowTickets = new System.Windows.Forms.FlowLayoutPanel();
            this.panelFiltros = new System.Windows.Forms.Panel();
            this.tblFiltros = new System.Windows.Forms.TableLayoutPanel();
            this.lblBuscar = new System.Windows.Forms.Label();
            this.txtBuscar = new System.Windows.Forms.TextBox();
            this.lblEstado = new System.Windows.Forms.Label();
            this.cboEstado = new System.Windows.Forms.ComboBox();
            this.lblTecnico = new System.Windows.Forms.Label();
            this.cboTecnico = new System.Windows.Forms.ComboBox();
            this.lblPrioridad = new System.Windows.Forms.Label();
            this.cboPrioridad = new System.Windows.Forms.ComboBox();
            this.lblBuscarId = new System.Windows.Forms.Label();
            this.txtBuscarId = new System.Windows.Forms.TextBox();
            this.lblCategoria = new System.Windows.Forms.Label();
            this.cboCategoria = new System.Windows.Forms.ComboBox();
            this.lblUbicacion = new System.Windows.Forms.Label();
            this.cboUbicacion = new System.Windows.Forms.ComboBox();
            this.lblFiltroSLA = new System.Windows.Forms.Label();
            this.cboFiltroSLA = new System.Windows.Forms.ComboBox();
            this.pnlBtnLimpiar = new System.Windows.Forms.Panel();
            this.btnLimpiarFiltros = new System.Windows.Forms.Button();
            this.panelMenu.SuspendLayout();
            this.panelTitulo.SuspendLayout();
            this.panelContenido.SuspendLayout();
            this.panelFiltros.SuspendLayout();
            this.tblFiltros.SuspendLayout();
            this.pnlBtnLimpiar.SuspendLayout();
            this.SuspendLayout();
            this.panelMenu.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.panelMenu.Controls.Add(this.btnBackup);
            this.panelMenu.Controls.Add(this.btnAnaliticas);
            this.panelMenu.Controls.Add(this.btnBitacora);
            this.panelMenu.Controls.Add(this.btnGestionMaestros);
            this.panelMenu.Controls.Add(this.btnGestionInventario);
            this.panelMenu.Controls.Add(this.btnCerrarSesion);
            this.panelMenu.Controls.Add(this.btnGestionAccesos);
            this.panelMenu.Controls.Add(this.btnCrearTicket);
            this.panelMenu.Controls.Add(this.btnCasos);
            this.panelMenu.Dock = System.Windows.Forms.DockStyle.Left;
            this.panelMenu.Location = new System.Drawing.Point(0, 0);
            this.panelMenu.Name = "panelMenu";
            this.panelMenu.Size = new System.Drawing.Size(180, 700);
            this.panelMenu.TabIndex = 0;
            this.btnBackup.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnBackup.FlatAppearance.BorderSize = 0;
            this.btnBackup.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnBackup.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.btnBackup.ForeColor = System.Drawing.Color.Gainsboro;
            this.btnBackup.Location = new System.Drawing.Point(0, 350);
            this.btnBackup.Name = "btnBackup";
            this.btnBackup.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.btnBackup.Size = new System.Drawing.Size(180, 50);
            this.btnBackup.TabIndex = 6;
            this.btnBackup.Text = "Backup";
            this.btnBackup.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBackup.UseVisualStyleBackColor = true;
            this.btnAnaliticas.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnAnaliticas.FlatAppearance.BorderSize = 0;
            this.btnAnaliticas.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAnaliticas.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.btnAnaliticas.ForeColor = System.Drawing.Color.Gainsboro;
            this.btnAnaliticas.Location = new System.Drawing.Point(0, 300);
            this.btnAnaliticas.Name = "btnAnaliticas";
            this.btnAnaliticas.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.btnAnaliticas.Size = new System.Drawing.Size(180, 50);
            this.btnAnaliticas.TabIndex = 5;
            this.btnAnaliticas.Text = "Analiticas";
            this.btnAnaliticas.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAnaliticas.UseVisualStyleBackColor = true;
            this.btnBitacora.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnBitacora.FlatAppearance.BorderSize = 0;
            this.btnBitacora.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnBitacora.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.btnBitacora.ForeColor = System.Drawing.Color.Gainsboro;
            this.btnBitacora.Location = new System.Drawing.Point(0, 250);
            this.btnBitacora.Name = "btnBitacora";
            this.btnBitacora.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.btnBitacora.Size = new System.Drawing.Size(180, 50);
            this.btnBitacora.TabIndex = 4;
            this.btnBitacora.Text = "Bitacora";
            this.btnBitacora.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBitacora.UseVisualStyleBackColor = true;
            this.btnGestionMaestros.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnGestionMaestros.FlatAppearance.BorderSize = 0;
            this.btnGestionMaestros.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnGestionMaestros.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.btnGestionMaestros.ForeColor = System.Drawing.Color.Gainsboro;
            this.btnGestionMaestros.Location = new System.Drawing.Point(0, 200);
            this.btnGestionMaestros.Name = "btnGestionMaestros";
            this.btnGestionMaestros.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.btnGestionMaestros.Size = new System.Drawing.Size(180, 50);
            this.btnGestionMaestros.TabIndex = 4;
            this.btnGestionMaestros.Text = "Gestion_Maestros";
            this.btnGestionMaestros.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGestionMaestros.UseVisualStyleBackColor = true;
            this.btnGestionInventario.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnGestionInventario.FlatAppearance.BorderSize = 0;
            this.btnGestionInventario.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnGestionInventario.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.btnGestionInventario.ForeColor = System.Drawing.Color.Gainsboro;
            this.btnGestionInventario.Location = new System.Drawing.Point(0, 150);
            this.btnGestionInventario.Name = "btnGestionInventario";
            this.btnGestionInventario.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.btnGestionInventario.Size = new System.Drawing.Size(180, 50);
            this.btnGestionInventario.TabIndex = 3;
            this.btnGestionInventario.Text = "Inventario";
            this.btnGestionInventario.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGestionInventario.UseVisualStyleBackColor = true;
            this.btnCerrarSesion.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.btnCerrarSesion.FlatAppearance.BorderSize = 0;
            this.btnCerrarSesion.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCerrarSesion.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.btnCerrarSesion.ForeColor = System.Drawing.Color.Gainsboro;
            this.btnCerrarSesion.Location = new System.Drawing.Point(0, 650);
            this.btnCerrarSesion.Name = "btnCerrarSesion";
            this.btnCerrarSesion.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.btnCerrarSesion.Size = new System.Drawing.Size(180, 50);
            this.btnCerrarSesion.TabIndex = 2;
            this.btnCerrarSesion.Text = "Cerrar_Sesion";
            this.btnCerrarSesion.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCerrarSesion.UseVisualStyleBackColor = true;
            this.btnCerrarSesion.Click += new System.EventHandler(this.btnCerrarSesion_Click_1);
            this.btnGestionAccesos.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnGestionAccesos.FlatAppearance.BorderSize = 0;
            this.btnGestionAccesos.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnGestionAccesos.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.btnGestionAccesos.ForeColor = System.Drawing.Color.Gainsboro;
            this.btnGestionAccesos.Location = new System.Drawing.Point(0, 100);
            this.btnGestionAccesos.Name = "btnGestionAccesos";
            this.btnGestionAccesos.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.btnGestionAccesos.Size = new System.Drawing.Size(180, 50);
            this.btnGestionAccesos.TabIndex = 2;
            this.btnGestionAccesos.Text = "Gestion_Accesos";
            this.btnGestionAccesos.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGestionAccesos.UseVisualStyleBackColor = true;
            this.btnCrearTicket.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnCrearTicket.FlatAppearance.BorderSize = 0;
            this.btnCrearTicket.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCrearTicket.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.btnCrearTicket.ForeColor = System.Drawing.Color.Gainsboro;
            this.btnCrearTicket.Location = new System.Drawing.Point(0, 50);
            this.btnCrearTicket.Name = "btnCrearTicket";
            this.btnCrearTicket.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.btnCrearTicket.Size = new System.Drawing.Size(180, 50);
            this.btnCrearTicket.TabIndex = 1;
            this.btnCrearTicket.Text = "Crear_Ticket";
            this.btnCrearTicket.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCrearTicket.UseVisualStyleBackColor = true;
            this.btnCasos.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnCasos.FlatAppearance.BorderSize = 0;
            this.btnCasos.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCasos.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.btnCasos.ForeColor = System.Drawing.Color.Gainsboro;
            this.btnCasos.Location = new System.Drawing.Point(0, 0);
            this.btnCasos.Name = "btnCasos";
            this.btnCasos.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.btnCasos.Size = new System.Drawing.Size(180, 50);
            this.btnCasos.TabIndex = 0;
            this.btnCasos.Text = "Casos";
            this.btnCasos.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCasos.UseVisualStyleBackColor = true;
            this.panelTitulo.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(70)))), ((int)(((byte)(90)))));
            this.panelTitulo.Controls.Add(this.lblTitulo);
            this.panelTitulo.Controls.Add(this.lblSubtitulo);
            this.panelTitulo.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelTitulo.Location = new System.Drawing.Point(180, 0);
            this.panelTitulo.Name = "panelTitulo";
            this.panelTitulo.Size = new System.Drawing.Size(1020, 100);
            this.panelTitulo.TabIndex = 1;
            this.lblTitulo.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblTitulo.Enabled = false;
            this.lblTitulo.Font = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold);
            this.lblTitulo.ForeColor = System.Drawing.Color.White;
            this.lblTitulo.Location = new System.Drawing.Point(0, 0);
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.Padding = new System.Windows.Forms.Padding(0, 10, 0, 0);
            this.lblTitulo.Size = new System.Drawing.Size(1020, 55);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblSubtitulo.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.lblSubtitulo.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lblSubtitulo.ForeColor = System.Drawing.Color.White;
            this.lblSubtitulo.Location = new System.Drawing.Point(0, 55);
            this.lblSubtitulo.Name = "lblSubtitulo";
            this.lblSubtitulo.Padding = new System.Windows.Forms.Padding(40, 0, 40, 10);
            this.lblSubtitulo.Size = new System.Drawing.Size(1020, 45);
            this.lblSubtitulo.TabIndex = 1;
            this.lblSubtitulo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.panelContenido.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            this.panelContenido.Controls.Add(this.flowTickets);
            this.panelContenido.Controls.Add(this.panelFiltros);
            this.panelContenido.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelContenido.Location = new System.Drawing.Point(180, 100);
            this.panelContenido.Name = "panelContenido";
            this.panelContenido.Size = new System.Drawing.Size(1020, 600);
            this.panelContenido.TabIndex = 2;
            this.flowTickets.AutoScroll = true;
            this.flowTickets.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            this.flowTickets.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flowTickets.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.flowTickets.Location = new System.Drawing.Point(0, 130);
            this.flowTickets.Name = "flowTickets";
            this.flowTickets.Padding = new System.Windows.Forms.Padding(10);
            this.flowTickets.Size = new System.Drawing.Size(1020, 470);
            this.flowTickets.TabIndex = 0;
            this.flowTickets.WrapContents = false;
            this.panelFiltros.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(65)))));
            this.panelFiltros.Controls.Add(this.tblFiltros);
            this.panelFiltros.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelFiltros.Location = new System.Drawing.Point(0, 0);
            this.panelFiltros.Name = "panelFiltros";
            this.panelFiltros.Padding = new System.Windows.Forms.Padding(15, 10, 15, 10);
            this.panelFiltros.Size = new System.Drawing.Size(1020, 130);
            this.panelFiltros.TabIndex = 1;
            this.tblFiltros.ColumnCount = 5;
            this.tblFiltros.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            this.tblFiltros.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            this.tblFiltros.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            this.tblFiltros.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            this.tblFiltros.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 28F));
            this.tblFiltros.Controls.Add(this.lblBuscar, 0, 0);
            this.tblFiltros.Controls.Add(this.txtBuscar, 0, 1);
            this.tblFiltros.Controls.Add(this.lblEstado, 1, 0);
            this.tblFiltros.Controls.Add(this.cboEstado, 1, 1);
            this.tblFiltros.Controls.Add(this.lblTecnico, 2, 0);
            this.tblFiltros.Controls.Add(this.cboTecnico, 2, 1);
            this.tblFiltros.Controls.Add(this.lblPrioridad, 3, 0);
            this.tblFiltros.Controls.Add(this.cboPrioridad, 3, 1);
            this.tblFiltros.Controls.Add(this.lblBuscarId, 0, 2);
            this.tblFiltros.Controls.Add(this.txtBuscarId, 0, 3);
            this.tblFiltros.Controls.Add(this.lblCategoria, 1, 2);
            this.tblFiltros.Controls.Add(this.cboCategoria, 1, 3);
            this.tblFiltros.Controls.Add(this.lblUbicacion, 2, 2);
            this.tblFiltros.Controls.Add(this.cboUbicacion, 2, 3);
            this.tblFiltros.Controls.Add(this.lblFiltroSLA, 3, 2);
            this.tblFiltros.Controls.Add(this.cboFiltroSLA, 3, 3);
            this.tblFiltros.Controls.Add(this.pnlBtnLimpiar, 4, 0);
            this.tblFiltros.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tblFiltros.Location = new System.Drawing.Point(15, 10);
            this.tblFiltros.Name = "tblFiltros";
            this.tblFiltros.RowCount = 4;
            this.tblFiltros.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tblFiltros.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tblFiltros.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tblFiltros.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tblFiltros.Size = new System.Drawing.Size(990, 110);
            this.tblFiltros.TabIndex = 0;
            this.lblBuscar.AutoSize = true;
            this.lblBuscar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblBuscar.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblBuscar.ForeColor = System.Drawing.Color.White;
            this.lblBuscar.Location = new System.Drawing.Point(3, 0);
            this.lblBuscar.Name = "lblBuscar";
            this.lblBuscar.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.lblBuscar.Size = new System.Drawing.Size(172, 20);
            this.lblBuscar.TabIndex = 0;
            this.lblBuscar.Text = " Buscar";
            this.lblBuscar.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.txtBuscar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(65)))), ((int)(((byte)(80)))));
            this.txtBuscar.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtBuscar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtBuscar.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtBuscar.ForeColor = System.Drawing.Color.White;
            this.txtBuscar.Location = new System.Drawing.Point(5, 23);
            this.txtBuscar.Margin = new System.Windows.Forms.Padding(5, 3, 5, 3);
            this.txtBuscar.Name = "txtBuscar";
            this.txtBuscar.Size = new System.Drawing.Size(168, 25);
            this.txtBuscar.TabIndex = 1;
            this.lblEstado.AutoSize = true;
            this.lblEstado.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblEstado.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblEstado.ForeColor = System.Drawing.Color.White;
            this.lblEstado.Location = new System.Drawing.Point(181, 0);
            this.lblEstado.Name = "lblEstado";
            this.lblEstado.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.lblEstado.Size = new System.Drawing.Size(172, 20);
            this.lblEstado.TabIndex = 2;
            this.lblEstado.Text = " Estado";
            this.lblEstado.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.cboEstado.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(65)))), ((int)(((byte)(80)))));
            this.cboEstado.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cboEstado.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboEstado.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboEstado.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cboEstado.ForeColor = System.Drawing.Color.White;
            this.cboEstado.FormattingEnabled = true;
            this.cboEstado.Location = new System.Drawing.Point(183, 23);
            this.cboEstado.Margin = new System.Windows.Forms.Padding(5, 3, 5, 3);
            this.cboEstado.Name = "cboEstado";
            this.cboEstado.Size = new System.Drawing.Size(168, 25);
            this.cboEstado.TabIndex = 3;
            this.lblTecnico.AutoSize = true;
            this.lblTecnico.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTecnico.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblTecnico.ForeColor = System.Drawing.Color.White;
            this.lblTecnico.Location = new System.Drawing.Point(359, 0);
            this.lblTecnico.Name = "lblTecnico";
            this.lblTecnico.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.lblTecnico.Size = new System.Drawing.Size(172, 20);
            this.lblTecnico.TabIndex = 4;
            this.lblTecnico.Text = "Tecnico";
            this.lblTecnico.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.cboTecnico.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(65)))), ((int)(((byte)(80)))));
            this.cboTecnico.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cboTecnico.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboTecnico.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboTecnico.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cboTecnico.ForeColor = System.Drawing.Color.White;
            this.cboTecnico.FormattingEnabled = true;
            this.cboTecnico.Location = new System.Drawing.Point(361, 23);
            this.cboTecnico.Margin = new System.Windows.Forms.Padding(5, 3, 5, 3);
            this.cboTecnico.Name = "cboTecnico";
            this.cboTecnico.Size = new System.Drawing.Size(168, 25);
            this.cboTecnico.TabIndex = 5;
            this.lblPrioridad.AutoSize = true;
            this.lblPrioridad.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPrioridad.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblPrioridad.ForeColor = System.Drawing.Color.White;
            this.lblPrioridad.Location = new System.Drawing.Point(537, 0);
            this.lblPrioridad.Name = "lblPrioridad";
            this.lblPrioridad.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.lblPrioridad.Size = new System.Drawing.Size(172, 20);
            this.lblPrioridad.TabIndex = 6;
            this.lblPrioridad.Text = " Prioridad";
            this.lblPrioridad.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.cboPrioridad.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(65)))), ((int)(((byte)(80)))));
            this.cboPrioridad.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cboPrioridad.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboPrioridad.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboPrioridad.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cboPrioridad.ForeColor = System.Drawing.Color.White;
            this.cboPrioridad.FormattingEnabled = true;
            this.cboPrioridad.Location = new System.Drawing.Point(539, 23);
            this.cboPrioridad.Margin = new System.Windows.Forms.Padding(5, 3, 5, 3);
            this.cboPrioridad.Name = "cboPrioridad";
            this.cboPrioridad.Size = new System.Drawing.Size(168, 25);
            this.cboPrioridad.TabIndex = 7;
            this.lblBuscarId.AutoSize = true;
            this.lblBuscarId.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblBuscarId.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblBuscarId.ForeColor = System.Drawing.Color.White;
            this.lblBuscarId.Location = new System.Drawing.Point(3, 55);
            this.lblBuscarId.Name = "lblBuscarId";
            this.lblBuscarId.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.lblBuscarId.Size = new System.Drawing.Size(172, 20);
            this.lblBuscarId.TabIndex = 8;
            this.lblBuscarId.Text = " ID";
            this.lblBuscarId.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.txtBuscarId.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(65)))), ((int)(((byte)(80)))));
            this.txtBuscarId.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtBuscarId.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtBuscarId.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtBuscarId.ForeColor = System.Drawing.Color.White;
            this.txtBuscarId.Location = new System.Drawing.Point(5, 78);
            this.txtBuscarId.Margin = new System.Windows.Forms.Padding(5, 3, 5, 3);
            this.txtBuscarId.Name = "txtBuscarId";
            this.txtBuscarId.Size = new System.Drawing.Size(168, 25);
            this.txtBuscarId.TabIndex = 9;
            this.lblCategoria.AutoSize = true;
            this.lblCategoria.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCategoria.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblCategoria.ForeColor = System.Drawing.Color.White;
            this.lblCategoria.Location = new System.Drawing.Point(181, 55);
            this.lblCategoria.Name = "lblCategoria";
            this.lblCategoria.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.lblCategoria.Size = new System.Drawing.Size(172, 20);
            this.lblCategoria.TabIndex = 10;
            this.lblCategoria.Text = " Categoria";
            this.lblCategoria.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.cboCategoria.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(65)))), ((int)(((byte)(80)))));
            this.cboCategoria.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cboCategoria.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboCategoria.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboCategoria.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cboCategoria.ForeColor = System.Drawing.Color.White;
            this.cboCategoria.FormattingEnabled = true;
            this.cboCategoria.Location = new System.Drawing.Point(183, 78);
            this.cboCategoria.Margin = new System.Windows.Forms.Padding(5, 3, 5, 3);
            this.cboCategoria.Name = "cboCategoria";
            this.cboCategoria.Size = new System.Drawing.Size(168, 25);
            this.cboCategoria.TabIndex = 11;
            this.lblUbicacion.AutoSize = true;
            this.lblUbicacion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblUbicacion.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblUbicacion.ForeColor = System.Drawing.Color.White;
            this.lblUbicacion.Location = new System.Drawing.Point(359, 55);
            this.lblUbicacion.Name = "lblUbicacion";
            this.lblUbicacion.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.lblUbicacion.Size = new System.Drawing.Size(172, 20);
            this.lblUbicacion.TabIndex = 12;
            this.lblUbicacion.Text = " Ubicacion";
            this.lblUbicacion.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.cboUbicacion.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(65)))), ((int)(((byte)(80)))));
            this.cboUbicacion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cboUbicacion.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboUbicacion.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboUbicacion.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cboUbicacion.ForeColor = System.Drawing.Color.White;
            this.cboUbicacion.FormattingEnabled = true;
            this.cboUbicacion.Location = new System.Drawing.Point(361, 78);
            this.cboUbicacion.Margin = new System.Windows.Forms.Padding(5, 3, 5, 3);
            this.cboUbicacion.Name = "cboUbicacion";
            this.cboUbicacion.Size = new System.Drawing.Size(168, 25);
            this.cboUbicacion.TabIndex = 13;
            this.lblFiltroSLA.AutoSize = true;
            this.lblFiltroSLA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroSLA.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblFiltroSLA.ForeColor = System.Drawing.Color.White;
            this.lblFiltroSLA.Location = new System.Drawing.Point(537, 55);
            this.lblFiltroSLA.Name = "lblFiltroSLA";
            this.lblFiltroSLA.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.lblFiltroSLA.Size = new System.Drawing.Size(172, 20);
            this.lblFiltroSLA.TabIndex = 14;
            this.lblFiltroSLA.Text = "Estado_SLA";
            this.lblFiltroSLA.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.cboFiltroSLA.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(65)))), ((int)(((byte)(80)))));
            this.cboFiltroSLA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cboFiltroSLA.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboFiltroSLA.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboFiltroSLA.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cboFiltroSLA.ForeColor = System.Drawing.Color.White;
            this.cboFiltroSLA.FormattingEnabled = true;
            this.cboFiltroSLA.Location = new System.Drawing.Point(539, 78);
            this.cboFiltroSLA.Margin = new System.Windows.Forms.Padding(5, 3, 5, 3);
            this.cboFiltroSLA.Name = "cboFiltroSLA";
            this.cboFiltroSLA.Size = new System.Drawing.Size(168, 25);
            this.cboFiltroSLA.TabIndex = 15;
            this.cboFiltroSLA.SelectedIndexChanged += new System.EventHandler(this.cboFiltroSLA_SelectedIndexChanged);
            this.pnlBtnLimpiar.Controls.Add(this.btnLimpiarFiltros);
            this.pnlBtnLimpiar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlBtnLimpiar.Location = new System.Drawing.Point(712, 0);
            this.pnlBtnLimpiar.Margin = new System.Windows.Forms.Padding(0);
            this.pnlBtnLimpiar.Name = "pnlBtnLimpiar";
            this.tblFiltros.SetRowSpan(this.pnlBtnLimpiar, 4);
            this.pnlBtnLimpiar.Size = new System.Drawing.Size(278, 110);
            this.pnlBtnLimpiar.TabIndex = 16;
            this.btnLimpiarFiltros.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnLimpiarFiltros.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(90)))));
            this.btnLimpiarFiltros.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnLimpiarFiltros.FlatAppearance.BorderSize = 0;
            this.btnLimpiarFiltros.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(70)))));
            this.btnLimpiarFiltros.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(85)))), ((int)(((byte)(105)))));
            this.btnLimpiarFiltros.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnLimpiarFiltros.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.btnLimpiarFiltros.ForeColor = System.Drawing.Color.White;
            this.btnLimpiarFiltros.Location = new System.Drawing.Point(51, 35);
            this.btnLimpiarFiltros.Name = "btnLimpiarFiltros";
            this.btnLimpiarFiltros.Size = new System.Drawing.Size(180, 40);
            this.btnLimpiarFiltros.TabIndex = 0;
            this.btnLimpiarFiltros.Text = "Limpiar Filtros";
            this.btnLimpiarFiltros.UseVisualStyleBackColor = false;
            this.btnLimpiarFiltros.Click += new System.EventHandler(this.btnLimpiarFiltros_Click_1);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1200, 700);
            this.Controls.Add(this.panelContenido);
            this.Controls.Add(this.panelTitulo);
            this.Controls.Add(this.panelMenu);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MinimumSize = new System.Drawing.Size(900, 600);
            this.Name = "VistaMainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Panel_Tecnico";
            this.Load += new System.EventHandler(this.VistaTecnicoForm_Load);
            this.panelMenu.ResumeLayout(false);
            this.panelTitulo.ResumeLayout(false);
            this.panelContenido.ResumeLayout(false);
            this.panelFiltros.ResumeLayout(false);
            this.tblFiltros.ResumeLayout(false);
            this.tblFiltros.PerformLayout();
            this.pnlBtnLimpiar.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        private System.Windows.Forms.Panel panelMenu;
        private System.Windows.Forms.Button btnCasos;
        private System.Windows.Forms.Button btnCrearTicket;
        private System.Windows.Forms.Button btnGestionAccesos;
        private System.Windows.Forms.Button btnCerrarSesion;
        private System.Windows.Forms.Button btnGestionInventario;
        private System.Windows.Forms.Button btnGestionMaestros;
        private System.Windows.Forms.Button btnBitacora;
        private System.Windows.Forms.Button btnAnaliticas;
        private System.Windows.Forms.Button btnBackup;
        private System.Windows.Forms.Panel panelTitulo;
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.Label lblSubtitulo;
        private System.Windows.Forms.Panel panelContenido;
        private System.Windows.Forms.FlowLayoutPanel flowTickets;
        private System.Windows.Forms.Panel panelFiltros;
        private System.Windows.Forms.TableLayoutPanel tblFiltros;
        private System.Windows.Forms.Label lblBuscar;
        private System.Windows.Forms.TextBox txtBuscar;
        private System.Windows.Forms.Label lblBuscarId;
        private System.Windows.Forms.TextBox txtBuscarId;
        private System.Windows.Forms.Label lblEstado;
        private System.Windows.Forms.ComboBox cboEstado;
        private System.Windows.Forms.Label lblCategoria;
        private System.Windows.Forms.ComboBox cboCategoria;
        private System.Windows.Forms.Label lblUbicacion;
        private System.Windows.Forms.ComboBox cboUbicacion;
        private System.Windows.Forms.Label lblTecnico;
        private System.Windows.Forms.ComboBox cboTecnico;
        private System.Windows.Forms.Label lblPrioridad;
        private System.Windows.Forms.ComboBox cboPrioridad;
        private System.Windows.Forms.Label lblFiltroSLA;
        private System.Windows.Forms.ComboBox cboFiltroSLA;
        private System.Windows.Forms.Panel pnlBtnLimpiar;
        private System.Windows.Forms.Button btnLimpiarFiltros;
    }
}
