﻿
namespace TicketPro.VistaCliente
{
    partial class CrearTicketCliente
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CrearTicketCliente));
            this.pnlBody = new System.Windows.Forms.Panel();
            this.tableLayoutMain = new System.Windows.Forms.TableLayoutPanel();
            this.lblTituloSeccion = new System.Windows.Forms.Label();
            this.lblTituloTicket = new System.Windows.Forms.Label();
            this.txtTitulo = new System.Windows.Forms.TextBox();
            this.lblDescripcion = new System.Windows.Forms.Label();
            this.txtDescripcion = new System.Windows.Forms.TextBox();
            this.pnlDetalles = new System.Windows.Forms.Panel();
            this.tableLayoutDetalles = new System.Windows.Forms.TableLayoutPanel();
            this.lblCategoria = new System.Windows.Forms.Label();
            this.cmbCategoria = new System.Windows.Forms.ComboBox();
            this.lblUbicacion = new System.Windows.Forms.Label();
            this.cmbUbicacion = new System.Windows.Forms.ComboBox();
            this.lblEquipo = new System.Windows.Forms.Label();
            this.cmbEquipo = new System.Windows.Forms.ComboBox();
            this.pnlAdjuntos = new System.Windows.Forms.Panel();
            this.lblAdjuntosSeccion = new System.Windows.Forms.Label();
            this.lstAdjuntos = new System.Windows.Forms.ListView();
            this.colNombre = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.colTamanio = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.pnlBotonesAdjuntos = new System.Windows.Forms.Panel();
            this.btnAgregarAdjunto = new System.Windows.Forms.Button();
            this.btnEliminarAdjunto = new System.Windows.Forms.Button();
            this.lblAdjuntosInfo = new System.Windows.Forms.Label();
            this.pnlFooter = new System.Windows.Forms.Panel();
            this.btnCrearTicket = new System.Windows.Forms.Button();
            this.btnCancelar = new System.Windows.Forms.Button();
            this.pnlBody.SuspendLayout();
            this.tableLayoutMain.SuspendLayout();
            this.pnlDetalles.SuspendLayout();
            this.tableLayoutDetalles.SuspendLayout();
            this.pnlAdjuntos.SuspendLayout();
            this.pnlBotonesAdjuntos.SuspendLayout();
            this.pnlFooter.SuspendLayout();
            this.SuspendLayout();
            this.pnlBody.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(55)))));
            this.pnlBody.Controls.Add(this.tableLayoutMain);
            this.pnlBody.Controls.Add(this.pnlFooter);
            this.pnlBody.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlBody.Location = new System.Drawing.Point(0, 0);
            this.pnlBody.Name = "pnlBody";
            this.pnlBody.Padding = new System.Windows.Forms.Padding(20);
            this.pnlBody.Size = new System.Drawing.Size(750, 650);
            this.pnlBody.TabIndex = 0;
            this.tableLayoutMain.ColumnCount = 1;
            this.tableLayoutMain.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutMain.Controls.Add(this.lblTituloSeccion, 0, 0);
            this.tableLayoutMain.Controls.Add(this.lblTituloTicket, 0, 1);
            this.tableLayoutMain.Controls.Add(this.txtTitulo, 0, 2);
            this.tableLayoutMain.Controls.Add(this.lblDescripcion, 0, 3);
            this.tableLayoutMain.Controls.Add(this.txtDescripcion, 0, 4);
            this.tableLayoutMain.Controls.Add(this.pnlDetalles, 0, 5);
            this.tableLayoutMain.Controls.Add(this.pnlAdjuntos, 0, 6);
            this.tableLayoutMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutMain.Location = new System.Drawing.Point(20, 20);
            this.tableLayoutMain.Name = "tableLayoutMain";
            this.tableLayoutMain.RowCount = 7;
            this.tableLayoutMain.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 45F));
            this.tableLayoutMain.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
            this.tableLayoutMain.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tableLayoutMain.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
            this.tableLayoutMain.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.tableLayoutMain.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 120F));
            this.tableLayoutMain.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutMain.Size = new System.Drawing.Size(710, 550);
            this.tableLayoutMain.TabIndex = 0;
            this.lblTituloSeccion.AutoSize = true;
            this.lblTituloSeccion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTituloSeccion.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            this.lblTituloSeccion.ForeColor = System.Drawing.Color.White;
            this.lblTituloSeccion.Location = new System.Drawing.Point(3, 0);
            this.lblTituloSeccion.Name = "lblTituloSeccion";
            this.lblTituloSeccion.Size = new System.Drawing.Size(704, 45);
            this.lblTituloSeccion.TabIndex = 0;
            this.lblTituloSeccion.Text = "Crear Nuevo Ticket";
            this.lblTituloSeccion.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblTituloTicket.AutoSize = true;
            this.lblTituloTicket.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTituloTicket.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblTituloTicket.ForeColor = System.Drawing.Color.Gainsboro;
            this.lblTituloTicket.Location = new System.Drawing.Point(3, 45);
            this.lblTituloTicket.Name = "lblTituloTicket";
            this.lblTituloTicket.Size = new System.Drawing.Size(704, 25);
            this.lblTituloTicket.TabIndex = 1;
            this.lblTituloTicket.Text = "Titulo del Ticket *";
            this.lblTituloTicket.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.txtTitulo.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(65)))));
            this.txtTitulo.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtTitulo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtTitulo.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtTitulo.ForeColor = System.Drawing.Color.White;
            this.txtTitulo.Location = new System.Drawing.Point(3, 73);
            this.txtTitulo.Name = "txtTitulo";
            this.txtTitulo.Size = new System.Drawing.Size(704, 25);
            this.txtTitulo.TabIndex = 2;
            this.lblDescripcion.AutoSize = true;
            this.lblDescripcion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDescripcion.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblDescripcion.ForeColor = System.Drawing.Color.Gainsboro;
            this.lblDescripcion.Location = new System.Drawing.Point(3, 105);
            this.lblDescripcion.Name = "lblDescripcion";
            this.lblDescripcion.Size = new System.Drawing.Size(704, 25);
            this.lblDescripcion.TabIndex = 3;
            this.lblDescripcion.Text = "Descripcion del Problema";
            this.lblDescripcion.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.txtDescripcion.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(65)))));
            this.txtDescripcion.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtDescripcion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtDescripcion.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtDescripcion.ForeColor = System.Drawing.Color.White;
            this.txtDescripcion.Location = new System.Drawing.Point(3, 133);
            this.txtDescripcion.Multiline = true;
            this.txtDescripcion.Name = "txtDescripcion";
            this.txtDescripcion.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtDescripcion.Size = new System.Drawing.Size(704, 84);
            this.txtDescripcion.TabIndex = 4;
            this.pnlDetalles.Controls.Add(this.tableLayoutDetalles);
            this.pnlDetalles.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlDetalles.Location = new System.Drawing.Point(3, 223);
            this.pnlDetalles.Name = "pnlDetalles";
            this.pnlDetalles.Size = new System.Drawing.Size(704, 114);
            this.pnlDetalles.TabIndex = 5;
            this.tableLayoutDetalles.ColumnCount = 3;
            this.tableLayoutDetalles.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.tableLayoutDetalles.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.tableLayoutDetalles.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.34F));
            this.tableLayoutDetalles.Controls.Add(this.lblCategoria, 0, 0);
            this.tableLayoutDetalles.Controls.Add(this.cmbCategoria, 0, 1);
            this.tableLayoutDetalles.Controls.Add(this.lblUbicacion, 1, 0);
            this.tableLayoutDetalles.Controls.Add(this.cmbUbicacion, 1, 1);
            this.tableLayoutDetalles.Controls.Add(this.lblEquipo, 2, 0);
            this.tableLayoutDetalles.Controls.Add(this.cmbEquipo, 2, 1);
            this.tableLayoutDetalles.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutDetalles.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutDetalles.Name = "tableLayoutDetalles";
            this.tableLayoutDetalles.RowCount = 2;
            this.tableLayoutDetalles.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
            this.tableLayoutDetalles.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tableLayoutDetalles.Size = new System.Drawing.Size(704, 114);
            this.tableLayoutDetalles.TabIndex = 0;
            this.lblCategoria.AutoSize = true;
            this.lblCategoria.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCategoria.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblCategoria.ForeColor = System.Drawing.Color.Gainsboro;
            this.lblCategoria.Location = new System.Drawing.Point(3, 0);
            this.lblCategoria.Name = "lblCategoria";
            this.lblCategoria.Size = new System.Drawing.Size(228, 25);
            this.lblCategoria.TabIndex = 0;
            this.lblCategoria.Text = "Categoria *";
            this.lblCategoria.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.cmbCategoria.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(65)))));
            this.cmbCategoria.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbCategoria.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCategoria.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbCategoria.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.cmbCategoria.ForeColor = System.Drawing.Color.White;
            this.cmbCategoria.FormattingEnabled = true;
            this.cmbCategoria.Location = new System.Drawing.Point(3, 28);
            this.cmbCategoria.Name = "cmbCategoria";
            this.cmbCategoria.Size = new System.Drawing.Size(228, 25);
            this.cmbCategoria.TabIndex = 1;
            this.lblUbicacion.AutoSize = true;
            this.lblUbicacion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblUbicacion.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblUbicacion.ForeColor = System.Drawing.Color.Gainsboro;
            this.lblUbicacion.Location = new System.Drawing.Point(237, 0);
            this.lblUbicacion.Name = "lblUbicacion";
            this.lblUbicacion.Size = new System.Drawing.Size(228, 25);
            this.lblUbicacion.TabIndex = 2;
            this.lblUbicacion.Text = "Ubicacion *";
            this.lblUbicacion.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.cmbUbicacion.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(65)))));
            this.cmbUbicacion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbUbicacion.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbUbicacion.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbUbicacion.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.cmbUbicacion.ForeColor = System.Drawing.Color.White;
            this.cmbUbicacion.FormattingEnabled = true;
            this.cmbUbicacion.Location = new System.Drawing.Point(237, 28);
            this.cmbUbicacion.Name = "cmbUbicacion";
            this.cmbUbicacion.Size = new System.Drawing.Size(228, 25);
            this.cmbUbicacion.TabIndex = 3;
            this.lblEquipo.AutoSize = true;
            this.lblEquipo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblEquipo.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblEquipo.ForeColor = System.Drawing.Color.Gainsboro;
            this.lblEquipo.Location = new System.Drawing.Point(471, 0);
            this.lblEquipo.Name = "lblEquipo";
            this.lblEquipo.Size = new System.Drawing.Size(230, 25);
            this.lblEquipo.TabIndex = 4;
            this.lblEquipo.Text = "Equipo (Opcional)";
            this.lblEquipo.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.cmbEquipo.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(65)))));
            this.cmbEquipo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbEquipo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbEquipo.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbEquipo.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.cmbEquipo.ForeColor = System.Drawing.Color.White;
            this.cmbEquipo.FormattingEnabled = true;
            this.cmbEquipo.Location = new System.Drawing.Point(471, 28);
            this.cmbEquipo.Name = "cmbEquipo";
            this.cmbEquipo.Size = new System.Drawing.Size(230, 25);
            this.cmbEquipo.TabIndex = 5;
            this.pnlAdjuntos.Controls.Add(this.lblAdjuntosSeccion);
            this.pnlAdjuntos.Controls.Add(this.lstAdjuntos);
            this.pnlAdjuntos.Controls.Add(this.pnlBotonesAdjuntos);
            this.pnlAdjuntos.Controls.Add(this.lblAdjuntosInfo);
            this.pnlAdjuntos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlAdjuntos.Location = new System.Drawing.Point(3, 343);
            this.pnlAdjuntos.Name = "pnlAdjuntos";
            this.pnlAdjuntos.Size = new System.Drawing.Size(704, 204);
            this.pnlAdjuntos.TabIndex = 6;
            this.lblAdjuntosSeccion.AutoSize = true;
            this.lblAdjuntosSeccion.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblAdjuntosSeccion.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblAdjuntosSeccion.ForeColor = System.Drawing.Color.White;
            this.lblAdjuntosSeccion.Location = new System.Drawing.Point(0, 0);
            this.lblAdjuntosSeccion.Name = "lblAdjuntosSeccion";
            this.lblAdjuntosSeccion.Padding = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.lblAdjuntosSeccion.Size = new System.Drawing.Size(157, 27);
            this.lblAdjuntosSeccion.TabIndex = 0;
            this.lblAdjuntosSeccion.Text = "Archivos Adjuntos";
            this.lstAdjuntos.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(65)))));
            this.lstAdjuntos.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lstAdjuntos.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.colNombre,
            this.colTamanio});
            this.lstAdjuntos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lstAdjuntos.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lstAdjuntos.ForeColor = System.Drawing.Color.White;
            this.lstAdjuntos.FullRowSelect = true;
            this.lstAdjuntos.HeaderStyle = System.Windows.Forms.ColumnHeaderStyle.Nonclickable;
            this.lstAdjuntos.HideSelection = false;
            this.lstAdjuntos.Location = new System.Drawing.Point(0, 27);
            this.lstAdjuntos.Name = "lstAdjuntos";
            this.lstAdjuntos.Size = new System.Drawing.Size(564, 159);
            this.lstAdjuntos.TabIndex = 1;
            this.lstAdjuntos.UseCompatibleStateImageBehavior = false;
            this.lstAdjuntos.View = System.Windows.Forms.View.Details;
            this.colNombre.Text = "Nombre del Archivo";
            this.colNombre.Width = 380;
            this.colTamanio.Text = "tamano";
            this.colTamanio.Width = 100;
            this.pnlBotonesAdjuntos.Controls.Add(this.btnAgregarAdjunto);
            this.pnlBotonesAdjuntos.Controls.Add(this.btnEliminarAdjunto);
            this.pnlBotonesAdjuntos.Dock = System.Windows.Forms.DockStyle.Right;
            this.pnlBotonesAdjuntos.Location = new System.Drawing.Point(564, 27);
            this.pnlBotonesAdjuntos.Name = "pnlBotonesAdjuntos";
            this.pnlBotonesAdjuntos.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.pnlBotonesAdjuntos.Size = new System.Drawing.Size(140, 159);
            this.pnlBotonesAdjuntos.TabIndex = 2;
            this.btnAgregarAdjunto.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(132)))), ((int)(((byte)(255)))));
            this.btnAgregarAdjunto.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnAgregarAdjunto.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnAgregarAdjunto.FlatAppearance.BorderSize = 0;
            this.btnAgregarAdjunto.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAgregarAdjunto.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.btnAgregarAdjunto.ForeColor = System.Drawing.Color.White;
            this.btnAgregarAdjunto.Location = new System.Drawing.Point(10, 0);
            this.btnAgregarAdjunto.Name = "btnAgregarAdjunto";
            this.btnAgregarAdjunto.Size = new System.Drawing.Size(130, 35);
            this.btnAgregarAdjunto.TabIndex = 0;
            this.btnAgregarAdjunto.Text = "+ Agregar";
            this.btnAgregarAdjunto.UseVisualStyleBackColor = false;
            this.btnAgregarAdjunto.Click += new System.EventHandler(this.btnAgregarAdjunto_Click);
            this.btnEliminarAdjunto.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(53)))), ((int)(((byte)(69)))));
            this.btnEliminarAdjunto.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnEliminarAdjunto.FlatAppearance.BorderSize = 0;
            this.btnEliminarAdjunto.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnEliminarAdjunto.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.btnEliminarAdjunto.ForeColor = System.Drawing.Color.White;
            this.btnEliminarAdjunto.Location = new System.Drawing.Point(10, 41);
            this.btnEliminarAdjunto.Name = "btnEliminarAdjunto";
            this.btnEliminarAdjunto.Size = new System.Drawing.Size(130, 35);
            this.btnEliminarAdjunto.TabIndex = 1;
            this.btnEliminarAdjunto.Text = "🗑️ Eliminar";
            this.btnEliminarAdjunto.UseVisualStyleBackColor = false;
            this.btnEliminarAdjunto.Click += new System.EventHandler(this.btnEliminarAdjunto_Click);
            this.lblAdjuntosInfo.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.lblAdjuntosInfo.Font = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Italic);
            this.lblAdjuntosInfo.ForeColor = System.Drawing.Color.Gray;
            this.lblAdjuntosInfo.Location = new System.Drawing.Point(0, 186);
            this.lblAdjuntosInfo.Name = "lblAdjuntosInfo";
            this.lblAdjuntosInfo.Size = new System.Drawing.Size(704, 18);
            this.lblAdjuntosInfo.TabIndex = 3;
            this.lblAdjuntosInfo.Text = "Max 10 MB por archivo. Permitidos: PDF, Word, Excel, imagenes, ZIP";
            this.lblAdjuntosInfo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.pnlFooter.Controls.Add(this.btnCrearTicket);
            this.pnlFooter.Controls.Add(this.btnCancelar);
            this.pnlFooter.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.pnlFooter.Location = new System.Drawing.Point(20, 570);
            this.pnlFooter.Name = "pnlFooter";
            this.pnlFooter.Size = new System.Drawing.Size(710, 60);
            this.pnlFooter.TabIndex = 1;
            this.btnCrearTicket.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnCrearTicket.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(204)))), ((int)(((byte)(113)))));
            this.btnCrearTicket.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnCrearTicket.FlatAppearance.BorderSize = 0;
            this.btnCrearTicket.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCrearTicket.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.btnCrearTicket.ForeColor = System.Drawing.Color.White;
            this.btnCrearTicket.Location = new System.Drawing.Point(550, 10);
            this.btnCrearTicket.Name = "btnCrearTicket";
            this.btnCrearTicket.Size = new System.Drawing.Size(150, 40);
            this.btnCrearTicket.TabIndex = 0;
            this.btnCrearTicket.Text = "Crear Ticket";
            this.btnCrearTicket.UseVisualStyleBackColor = false;
            this.btnCrearTicket.Click += new System.EventHandler(this.btnCrearTicket_Click);
            this.btnCancelar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnCancelar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(108)))), ((int)(((byte)(117)))), ((int)(((byte)(125)))));
            this.btnCancelar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnCancelar.FlatAppearance.BorderSize = 0;
            this.btnCancelar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCancelar.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.btnCancelar.ForeColor = System.Drawing.Color.White;
            this.btnCancelar.Location = new System.Drawing.Point(390, 10);
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.Size = new System.Drawing.Size(150, 40);
            this.btnCancelar.TabIndex = 1;
            this.btnCancelar.Text = "Cancelar";
            this.btnCancelar.UseVisualStyleBackColor = false;
            this.btnCancelar.Click += new System.EventHandler(this.btnCancelar_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.ClientSize = new System.Drawing.Size(750, 650);
            this.Controls.Add(this.pnlBody);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Sizable;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MinimumSize = new System.Drawing.Size(700, 600);
            this.Name = "CrearTicketCliente";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Crear Ticket - TicketsPro";
            this.pnlBody.ResumeLayout(false);
            this.tableLayoutMain.ResumeLayout(false);
            this.tableLayoutMain.PerformLayout();
            this.pnlDetalles.ResumeLayout(false);
            this.tableLayoutDetalles.ResumeLayout(false);
            this.tableLayoutDetalles.PerformLayout();
            this.pnlAdjuntos.ResumeLayout(false);
            this.pnlAdjuntos.PerformLayout();
            this.pnlBotonesAdjuntos.ResumeLayout(false);
            this.pnlFooter.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        private System.Windows.Forms.Panel pnlBody;
        private System.Windows.Forms.TableLayoutPanel tableLayoutMain;
        private System.Windows.Forms.Label lblTituloSeccion;
        private System.Windows.Forms.Label lblTituloTicket;
        private System.Windows.Forms.TextBox txtTitulo;
        private System.Windows.Forms.Label lblDescripcion;
        private System.Windows.Forms.TextBox txtDescripcion;
        private System.Windows.Forms.Panel pnlDetalles;
        private System.Windows.Forms.TableLayoutPanel tableLayoutDetalles;
        private System.Windows.Forms.Label lblCategoria;
        private System.Windows.Forms.ComboBox cmbCategoria;
        private System.Windows.Forms.Label lblUbicacion;
        private System.Windows.Forms.ComboBox cmbUbicacion;
        private System.Windows.Forms.Label lblEquipo;
        private System.Windows.Forms.ComboBox cmbEquipo;
        private System.Windows.Forms.Panel pnlAdjuntos;
        private System.Windows.Forms.Label lblAdjuntosSeccion;
        private System.Windows.Forms.ListView lstAdjuntos;
        private System.Windows.Forms.ColumnHeader colNombre;
        private System.Windows.Forms.ColumnHeader colTamanio;
        private System.Windows.Forms.Panel pnlBotonesAdjuntos;
        private System.Windows.Forms.Button btnAgregarAdjunto;
        private System.Windows.Forms.Button btnEliminarAdjunto;
        private System.Windows.Forms.Label lblAdjuntosInfo;
        private System.Windows.Forms.Panel pnlFooter;
        private System.Windows.Forms.Button btnCrearTicket;
        private System.Windows.Forms.Button btnCancelar;
    }
}
