using System.Windows.Forms;
namespace TicketPro.Tecnico
{
    partial class FormNuevoEquipo
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.panelDatos = new System.Windows.Forms.Panel();
            this.lblTituloDatos = new System.Windows.Forms.Label();
            this.lblInventario = new System.Windows.Forms.Label();
            this.txtInventario = new System.Windows.Forms.TextBox();
            this.lblModelo = new System.Windows.Forms.Label();
            this.txtModelo = new System.Windows.Forms.TextBox();
            this.lblUbicacion = new System.Windows.Forms.Label();
            this.txtUbicacion = new System.Windows.Forms.TextBox();
            this.lblProcesador = new System.Windows.Forms.Label();
            this.txtProcesador = new System.Windows.Forms.TextBox();
            this.lblTipo = new System.Windows.Forms.Label();
            this.cmbTipo = new System.Windows.Forms.ComboBox();
            this.panelRAM = new System.Windows.Forms.Panel();
            this.lblRam = new System.Windows.Forms.Label();
            this.btnAddRam = new System.Windows.Forms.Button();
            this.flowRamModules = new System.Windows.Forms.FlowLayoutPanel();
            this.panelROM = new System.Windows.Forms.Panel();
            this.lblRom = new System.Windows.Forms.Label();
            this.btnAddRom = new System.Windows.Forms.Button();
            this.flowRomModules = new System.Windows.Forms.FlowLayoutPanel();
            this.btnGuardar = new System.Windows.Forms.Button();
            this.btnCancelar = new System.Windows.Forms.Button();
            this.panelDatos.SuspendLayout();
            this.panelRAM.SuspendLayout();
            this.panelROM.SuspendLayout();
            this.SuspendLayout();
            this.panelDatos.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(60)))));
            this.panelDatos.Controls.Add(this.lblTituloDatos);
            this.panelDatos.Controls.Add(this.lblInventario);
            this.panelDatos.Controls.Add(this.txtInventario);
            this.panelDatos.Controls.Add(this.lblModelo);
            this.panelDatos.Controls.Add(this.txtModelo);
            this.panelDatos.Controls.Add(this.lblUbicacion);
            this.panelDatos.Controls.Add(this.txtUbicacion);
            this.panelDatos.Controls.Add(this.lblProcesador);
            this.panelDatos.Controls.Add(this.txtProcesador);
            this.panelDatos.Controls.Add(this.lblTipo);
            this.panelDatos.Controls.Add(this.cmbTipo);
            this.panelDatos.Location = new System.Drawing.Point(30, 20);
            this.panelDatos.Name = "panelDatos";
            this.panelDatos.Size = new System.Drawing.Size(540, 240);
            this.panelDatos.TabIndex = 0;
            this.lblTituloDatos.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold);
            this.lblTituloDatos.ForeColor = System.Drawing.Color.White;
            this.lblTituloDatos.Location = new System.Drawing.Point(10, 10);
            this.lblTituloDatos.Name = "lblTituloDatos";
            this.lblTituloDatos.Size = new System.Drawing.Size(100, 23);
            this.lblTituloDatos.TabIndex = 0;
            this.lblTituloDatos.Text = "Inventario_NuevoEquipo_LabelTituloDatos";
            this.lblInventario.ForeColor = System.Drawing.Color.White;
            this.lblInventario.Location = new System.Drawing.Point(10, 50);
            this.lblInventario.Name = "lblInventario";
            this.lblInventario.Size = new System.Drawing.Size(100, 23);
            this.lblInventario.TabIndex = 1;
            this.lblInventario.Text = "Inventario_NuevoEquipo_LabelInventario";
            this.txtInventario.Location = new System.Drawing.Point(150, 47);
            this.txtInventario.Name = "txtInventario";
            this.txtInventario.Size = new System.Drawing.Size(300, 20);
            this.txtInventario.TabIndex = 2;
            this.lblModelo.ForeColor = System.Drawing.Color.White;
            this.lblModelo.Location = new System.Drawing.Point(10, 90);
            this.lblModelo.Name = "lblModelo";
            this.lblModelo.Size = new System.Drawing.Size(100, 23);
            this.lblModelo.TabIndex = 3;
            this.lblModelo.Text = "Inventario_NuevoEquipo_LabelModelo";
            this.txtModelo.Location = new System.Drawing.Point(150, 87);
            this.txtModelo.Name = "txtModelo";
            this.txtModelo.Size = new System.Drawing.Size(300, 20);
            this.txtModelo.TabIndex = 4;
            this.lblUbicacion.ForeColor = System.Drawing.Color.White;
            this.lblUbicacion.Location = new System.Drawing.Point(10, 130);
            this.lblUbicacion.Name = "lblUbicacion";
            this.lblUbicacion.Size = new System.Drawing.Size(100, 23);
            this.lblUbicacion.TabIndex = 5;
            this.lblUbicacion.Text = "Inventario_NuevoEquipo_LabelUbicacion";
            this.txtUbicacion.Location = new System.Drawing.Point(150, 127);
            this.txtUbicacion.Name = "txtUbicacion";
            this.txtUbicacion.Size = new System.Drawing.Size(300, 20);
            this.txtUbicacion.TabIndex = 6;
            this.lblProcesador.ForeColor = System.Drawing.Color.White;
            this.lblProcesador.Location = new System.Drawing.Point(10, 170);
            this.lblProcesador.Name = "lblProcesador";
            this.lblProcesador.Size = new System.Drawing.Size(100, 23);
            this.lblProcesador.TabIndex = 7;
            this.lblProcesador.Text = "Inventario_NuevoEquipo_LabelProcesador";
            this.txtProcesador.Location = new System.Drawing.Point(150, 167);
            this.txtProcesador.Name = "txtProcesador";
            this.txtProcesador.Size = new System.Drawing.Size(300, 20);
            this.txtProcesador.TabIndex = 8;
            this.lblTipo.ForeColor = System.Drawing.Color.White;
            this.lblTipo.Location = new System.Drawing.Point(10, 210);
            this.lblTipo.Name = "lblTipo";
            this.lblTipo.Size = new System.Drawing.Size(100, 23);
            this.lblTipo.TabIndex = 9;
            this.lblTipo.Text = "Inventario_NuevoEquipo_LabelTipo";
            this.cmbTipo.Location = new System.Drawing.Point(150, 207);
            this.cmbTipo.Name = "cmbTipo";
            this.cmbTipo.Size = new System.Drawing.Size(200, 21);
            this.cmbTipo.TabIndex = 10;
            this.panelRAM.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(60)))));
            this.panelRAM.Controls.Add(this.lblRam);
            this.panelRAM.Controls.Add(this.btnAddRam);
            this.panelRAM.Controls.Add(this.flowRamModules);
            this.panelRAM.Location = new System.Drawing.Point(30, 280);
            this.panelRAM.Name = "panelRAM";
            this.panelRAM.Size = new System.Drawing.Size(540, 200);
            this.panelRAM.TabIndex = 1;
            this.lblRam.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold);
            this.lblRam.ForeColor = System.Drawing.Color.White;
            this.lblRam.Location = new System.Drawing.Point(10, 10);
            this.lblRam.Name = "lblRam";
            this.lblRam.Size = new System.Drawing.Size(100, 23);
            this.lblRam.TabIndex = 0;
            this.lblRam.Text = "Inventario_NuevoEquipo_LabelRAM";
            this.btnAddRam.Location = new System.Drawing.Point(10, 45);
            this.btnAddRam.Name = "btnAddRam";
            this.btnAddRam.Size = new System.Drawing.Size(200, 28);
            this.btnAddRam.TabIndex = 1;
            this.btnAddRam.Text = "Inventario_NuevoEquipo_BotonAgregarRAM";
            this.flowRamModules.AutoScroll = true;
            this.flowRamModules.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.flowRamModules.Location = new System.Drawing.Point(10, 80);
            this.flowRamModules.Name = "flowRamModules";
            this.flowRamModules.Size = new System.Drawing.Size(510, 100);
            this.flowRamModules.TabIndex = 2;
            this.panelROM.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(60)))));
            this.panelROM.Controls.Add(this.lblRom);
            this.panelROM.Controls.Add(this.btnAddRom);
            this.panelROM.Controls.Add(this.flowRomModules);
            this.panelROM.Location = new System.Drawing.Point(30, 500);
            this.panelROM.Name = "panelROM";
            this.panelROM.Size = new System.Drawing.Size(540, 200);
            this.panelROM.TabIndex = 2;
            this.lblRom.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold);
            this.lblRom.ForeColor = System.Drawing.Color.White;
            this.lblRom.Location = new System.Drawing.Point(10, 10);
            this.lblRom.Name = "lblRom";
            this.lblRom.Size = new System.Drawing.Size(100, 23);
            this.lblRom.TabIndex = 0;
            this.lblRom.Text = "Inventario_NuevoEquipo_LabelROM";
            this.btnAddRom.Location = new System.Drawing.Point(10, 45);
            this.btnAddRom.Name = "btnAddRom";
            this.btnAddRom.Size = new System.Drawing.Size(260, 28);
            this.btnAddRom.TabIndex = 1;
            this.btnAddRom.Text = "Inventario_NuevoEquipo_BotonAgregarROM";
            this.flowRomModules.AutoScroll = true;
            this.flowRomModules.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.flowRomModules.Location = new System.Drawing.Point(10, 80);
            this.flowRomModules.Name = "flowRomModules";
            this.flowRomModules.Size = new System.Drawing.Size(510, 100);
            this.flowRomModules.TabIndex = 2;
            this.btnGuardar.Location = new System.Drawing.Point(330, 720);
            this.btnGuardar.Name = "btnGuardar";
            this.btnGuardar.Size = new System.Drawing.Size(120, 35);
            this.btnGuardar.TabIndex = 3;
            this.btnGuardar.Text = "Inventario_NuevoEquipo_BotonGuardar";
            this.btnGuardar.Click += new System.EventHandler(this.btnGuardar_Click);
            this.btnCancelar.Location = new System.Drawing.Point(460, 720);
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.Size = new System.Drawing.Size(120, 35);
            this.btnCancelar.TabIndex = 4;
            this.btnCancelar.Text = "Inventario_NuevoEquipo_BotonCancelar";
            this.ClientSize = new System.Drawing.Size(600, 780);
            this.Controls.Add(this.panelDatos);
            this.Controls.Add(this.panelRAM);
            this.Controls.Add(this.panelROM);
            this.Controls.Add(this.btnGuardar);
            this.Controls.Add(this.btnCancelar);
            this.Name = "FormNuevoEquipo";
            this.Text = "Inventario_NuevoEquipo_Form_Titulo";
            this.Load += new System.EventHandler(this.FormNuevoEquipo_Load);
            this.panelDatos.ResumeLayout(false);
            this.panelDatos.PerformLayout();
            this.panelRAM.ResumeLayout(false);
            this.panelROM.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        private Panel panelDatos;
        private Panel panelRAM;
        private Panel panelROM;
        private Label lblTituloDatos;
        private Label lblInventario;
        private Label lblModelo;
        private Label lblUbicacion;
        private Label lblProcesador;
        private Label lblTipo;
        private Label lblRam;
        private Label lblRom;
        private TextBox txtInventario;
        private TextBox txtModelo;
        private TextBox txtUbicacion;
        private TextBox txtProcesador;
        private ComboBox cmbTipo;
        private FlowLayoutPanel flowRamModules;
        private Button btnAddRam;
        private FlowLayoutPanel flowRomModules;
        private Button btnAddRom;
        private Button btnGuardar;
        private Button btnCancelar;
    }
}
