using System.Windows.Forms;
namespace TicketPro.Inventario
{
    partial class FormDetalleEquipo
    {
        private System.ComponentModel.IContainer components = null;
        private Panel panelInfo;
        private TableLayoutPanel tblInfo;
        private Label lblTitulo;
        private Label lblModelo;
        private TextBox txtModelo;
        private Label lblInventario;
        private TextBox txtInventario;
        private Label lblProcesador;
        private TextBox txtProcesador;
        private Label lblRAM;
        private TextBox txtRAM;
        private Label lblROM;
        private TextBox txtROM;
        private Label lblUsuarioAsignado;
        private TextBox txtUsuarioAsignado;
        private Label lblSeleccionarUsuario;
        private ComboBox cmbUsuarios;
        private Button btnAsignarUsuario;
        private Button btnQuitarUsuario;
        private Panel panelRelaciones;
        private TableLayoutPanel tblRelaciones;
        private Panel pnlDisponibles;
        private Panel pnlAsignados;
        private Panel pnlBotonesRelacion;
        private Label lblDisponiblesCount;
        private Label lblAsignadosCount;
        private TextBox txtBuscarDisponibles;
        private TextBox txtBuscarAsignados;
        private ListBox lstDisponibles;
        private ListBox lstAsignados;
        private Button btnAgregar;
        private Button btnQuitar;
        private Button btnGuardar;
        private Button btnCerrar;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormDetalleEquipo));
            this.panelInfo = new System.Windows.Forms.Panel();
            this.tblInfo = new System.Windows.Forms.TableLayoutPanel();
            this.lblModelo = new System.Windows.Forms.Label();
            this.txtModelo = new System.Windows.Forms.TextBox();
            this.lblInventario = new System.Windows.Forms.Label();
            this.txtInventario = new System.Windows.Forms.TextBox();
            this.lblProcesador = new System.Windows.Forms.Label();
            this.txtProcesador = new System.Windows.Forms.TextBox();
            this.lblRAM = new System.Windows.Forms.Label();
            this.txtRAM = new System.Windows.Forms.TextBox();
            this.lblROM = new System.Windows.Forms.Label();
            this.txtROM = new System.Windows.Forms.TextBox();
            this.lblUsuarioAsignado = new System.Windows.Forms.Label();
            this.txtUsuarioAsignado = new System.Windows.Forms.TextBox();
            this.lblSeleccionarUsuario = new System.Windows.Forms.Label();
            this.cmbUsuarios = new System.Windows.Forms.ComboBox();
            this.btnAsignarUsuario = new System.Windows.Forms.Button();
            this.btnQuitarUsuario = new System.Windows.Forms.Button();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.panelRelaciones = new System.Windows.Forms.Panel();
            this.tblRelaciones = new System.Windows.Forms.TableLayoutPanel();
            this.pnlDisponibles = new System.Windows.Forms.Panel();
            this.lstDisponibles = new System.Windows.Forms.ListBox();
            this.txtBuscarDisponibles = new System.Windows.Forms.TextBox();
            this.lblDisponiblesCount = new System.Windows.Forms.Label();
            this.pnlBotonesRelacion = new System.Windows.Forms.Panel();
            this.btnAgregar = new System.Windows.Forms.Button();
            this.btnQuitar = new System.Windows.Forms.Button();
            this.pnlAsignados = new System.Windows.Forms.Panel();
            this.lstAsignados = new System.Windows.Forms.ListBox();
            this.txtBuscarAsignados = new System.Windows.Forms.TextBox();
            this.lblAsignadosCount = new System.Windows.Forms.Label();
            this.btnGuardar = new System.Windows.Forms.Button();
            this.btnCerrar = new System.Windows.Forms.Button();
            this.panelInfo.SuspendLayout();
            this.tblInfo.SuspendLayout();
            this.panelRelaciones.SuspendLayout();
            this.tblRelaciones.SuspendLayout();
            this.pnlDisponibles.SuspendLayout();
            this.pnlBotonesRelacion.SuspendLayout();
            this.pnlAsignados.SuspendLayout();
            this.SuspendLayout();
            this.panelInfo.Controls.Add(this.tblInfo);
            this.panelInfo.Controls.Add(this.lblTitulo);
            this.panelInfo.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelInfo.Location = new System.Drawing.Point(0, 0);
            this.panelInfo.Name = "panelInfo";
            this.panelInfo.Padding = new System.Windows.Forms.Padding(15, 10, 15, 10);
            this.panelInfo.Size = new System.Drawing.Size(1061, 160);
            this.panelInfo.TabIndex = 3;
            this.tblInfo.ColumnCount = 5;
            this.tblInfo.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tblInfo.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tblInfo.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tblInfo.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tblInfo.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tblInfo.Controls.Add(this.lblModelo, 0, 0);
            this.tblInfo.Controls.Add(this.txtModelo, 0, 1);
            this.tblInfo.Controls.Add(this.lblInventario, 1, 0);
            this.tblInfo.Controls.Add(this.txtInventario, 1, 1);
            this.tblInfo.Controls.Add(this.lblProcesador, 2, 0);
            this.tblInfo.Controls.Add(this.txtProcesador, 2, 1);
            this.tblInfo.Controls.Add(this.lblRAM, 3, 0);
            this.tblInfo.Controls.Add(this.txtRAM, 3, 1);
            this.tblInfo.Controls.Add(this.lblROM, 4, 0);
            this.tblInfo.Controls.Add(this.txtROM, 4, 1);
            this.tblInfo.Controls.Add(this.lblUsuarioAsignado, 0, 2);
            this.tblInfo.Controls.Add(this.txtUsuarioAsignado, 0, 3);
            this.tblInfo.Controls.Add(this.lblSeleccionarUsuario, 2, 2);
            this.tblInfo.Controls.Add(this.cmbUsuarios, 2, 3);
            this.tblInfo.Controls.Add(this.btnAsignarUsuario, 3, 3);
            this.tblInfo.Controls.Add(this.btnQuitarUsuario, 4, 3);
            this.tblInfo.Dock = System.Windows.Forms.DockStyle.Top;
            this.tblInfo.Location = new System.Drawing.Point(15, 35);
            this.tblInfo.Name = "tblInfo";
            this.tblInfo.RowCount = 4;
            this.tblInfo.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
            this.tblInfo.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            this.tblInfo.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
            this.tblInfo.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            this.tblInfo.Size = new System.Drawing.Size(1031, 114);
            this.tblInfo.TabIndex = 16;
            this.lblModelo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblModelo.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblModelo.Location = new System.Drawing.Point(3, 0);
            this.lblModelo.Name = "lblModelo";
            this.lblModelo.Size = new System.Drawing.Size(200, 25);
            this.lblModelo.TabIndex = 1;
            this.lblModelo.Text = "Inventario_DetalleEquipo_LabelModelo";
            this.lblModelo.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.txtModelo.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.txtModelo.Location = new System.Drawing.Point(3, 31);
            this.txtModelo.Name = "txtModelo";
            this.txtModelo.Size = new System.Drawing.Size(200, 20);
            this.txtModelo.TabIndex = 2;
            this.lblInventario.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblInventario.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblInventario.Location = new System.Drawing.Point(209, 0);
            this.lblInventario.Name = "lblInventario";
            this.lblInventario.Size = new System.Drawing.Size(200, 25);
            this.lblInventario.TabIndex = 3;
            this.lblInventario.Text = "Inventario_DetalleEquipo_LabelInventario";
            this.lblInventario.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.txtInventario.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.txtInventario.Location = new System.Drawing.Point(209, 31);
            this.txtInventario.Name = "txtInventario";
            this.txtInventario.Size = new System.Drawing.Size(200, 20);
            this.txtInventario.TabIndex = 4;
            this.lblProcesador.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblProcesador.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblProcesador.Location = new System.Drawing.Point(415, 0);
            this.lblProcesador.Name = "lblProcesador";
            this.lblProcesador.Size = new System.Drawing.Size(200, 25);
            this.lblProcesador.TabIndex = 5;
            this.lblProcesador.Text = "Inventario_DetalleEquipo_LabelProcesador";
            this.lblProcesador.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.txtProcesador.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.txtProcesador.Location = new System.Drawing.Point(415, 31);
            this.txtProcesador.Name = "txtProcesador";
            this.txtProcesador.Size = new System.Drawing.Size(200, 20);
            this.txtProcesador.TabIndex = 6;
            this.lblRAM.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRAM.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblRAM.Location = new System.Drawing.Point(621, 0);
            this.lblRAM.Name = "lblRAM";
            this.lblRAM.Size = new System.Drawing.Size(200, 25);
            this.lblRAM.TabIndex = 7;
            this.lblRAM.Text = "Inventario_DetalleEquipo_LabelRAM";
            this.lblRAM.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.txtRAM.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.txtRAM.Location = new System.Drawing.Point(621, 31);
            this.txtRAM.Name = "txtRAM";
            this.txtRAM.Size = new System.Drawing.Size(200, 20);
            this.txtRAM.TabIndex = 8;
            this.lblROM.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblROM.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblROM.Location = new System.Drawing.Point(827, 0);
            this.lblROM.Name = "lblROM";
            this.lblROM.Size = new System.Drawing.Size(201, 25);
            this.lblROM.TabIndex = 9;
            this.lblROM.Text = "Inventario_DetalleEquipo_LabelROM";
            this.lblROM.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.txtROM.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.txtROM.Location = new System.Drawing.Point(827, 31);
            this.txtROM.Name = "txtROM";
            this.txtROM.Size = new System.Drawing.Size(201, 20);
            this.txtROM.TabIndex = 10;
            this.tblInfo.SetColumnSpan(this.lblUsuarioAsignado, 2);
            this.lblUsuarioAsignado.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblUsuarioAsignado.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblUsuarioAsignado.Location = new System.Drawing.Point(3, 57);
            this.lblUsuarioAsignado.Name = "lblUsuarioAsignado";
            this.lblUsuarioAsignado.Size = new System.Drawing.Size(406, 25);
            this.lblUsuarioAsignado.TabIndex = 11;
            this.lblUsuarioAsignado.Text = "Inventario_DetalleEquipo_LabelUsuario";
            this.lblUsuarioAsignado.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.txtUsuarioAsignado.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.tblInfo.SetColumnSpan(this.txtUsuarioAsignado, 2);
            this.txtUsuarioAsignado.Location = new System.Drawing.Point(3, 88);
            this.txtUsuarioAsignado.Name = "txtUsuarioAsignado";
            this.txtUsuarioAsignado.ReadOnly = true;
            this.txtUsuarioAsignado.Size = new System.Drawing.Size(406, 20);
            this.txtUsuarioAsignado.TabIndex = 12;
            this.lblSeleccionarUsuario.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblSeleccionarUsuario.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblSeleccionarUsuario.Location = new System.Drawing.Point(415, 57);
            this.lblSeleccionarUsuario.Name = "lblSeleccionarUsuario";
            this.lblSeleccionarUsuario.Size = new System.Drawing.Size(200, 25);
            this.lblSeleccionarUsuario.TabIndex = 16;
            this.lblSeleccionarUsuario.Text = "Inventario_DetalleEquipo_LabelSeleccionarUsuario";
            this.lblSeleccionarUsuario.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.cmbUsuarios.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.cmbUsuarios.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbUsuarios.FormattingEnabled = true;
            this.cmbUsuarios.Location = new System.Drawing.Point(415, 87);
            this.cmbUsuarios.Name = "cmbUsuarios";
            this.cmbUsuarios.Size = new System.Drawing.Size(200, 21);
            this.cmbUsuarios.TabIndex = 13;
            this.btnAsignarUsuario.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAsignarUsuario.Location = new System.Drawing.Point(621, 85);
            this.btnAsignarUsuario.Margin = new System.Windows.Forms.Padding(3, 3, 5, 3);
            this.btnAsignarUsuario.Name = "btnAsignarUsuario";
            this.btnAsignarUsuario.Size = new System.Drawing.Size(198, 26);
            this.btnAsignarUsuario.TabIndex = 14;
            this.btnAsignarUsuario.Text = "Inventario_DetalleEquipo_BotonAsignarUsuario";
            this.btnAsignarUsuario.Click += new System.EventHandler(this.btnAsignarUsuario_Click);
            this.btnQuitarUsuario.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.btnQuitarUsuario.Location = new System.Drawing.Point(827, 85);
            this.btnQuitarUsuario.Name = "btnQuitarUsuario";
            this.btnQuitarUsuario.Size = new System.Drawing.Size(201, 26);
            this.btnQuitarUsuario.TabIndex = 15;
            this.btnQuitarUsuario.Text = "Inventario_DetalleEquipo_BotonQuitarUsuario";
            this.btnQuitarUsuario.Click += new System.EventHandler(this.btnQuitarUsuario_Click);
            this.lblTitulo.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblTitulo.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.lblTitulo.Location = new System.Drawing.Point(15, 10);
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.Size = new System.Drawing.Size(1031, 25);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.Text = "Inventario_DetalleEquipo_Form_Titulo";
            this.panelRelaciones.Controls.Add(this.tblRelaciones);
            this.panelRelaciones.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelRelaciones.Location = new System.Drawing.Point(0, 160);
            this.panelRelaciones.Name = "panelRelaciones";
            this.panelRelaciones.Padding = new System.Windows.Forms.Padding(15, 10, 15, 10);
            this.panelRelaciones.Size = new System.Drawing.Size(1061, 431);
            this.panelRelaciones.TabIndex = 2;
            this.tblRelaciones.ColumnCount = 3;
            this.tblRelaciones.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 47.5F));
            this.tblRelaciones.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.tblRelaciones.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 47.5F));
            this.tblRelaciones.Controls.Add(this.pnlDisponibles, 0, 0);
            this.tblRelaciones.Controls.Add(this.pnlBotonesRelacion, 1, 0);
            this.tblRelaciones.Controls.Add(this.pnlAsignados, 2, 0);
            this.tblRelaciones.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tblRelaciones.Location = new System.Drawing.Point(15, 10);
            this.tblRelaciones.Name = "tblRelaciones";
            this.tblRelaciones.RowCount = 1;
            this.tblRelaciones.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tblRelaciones.Size = new System.Drawing.Size(1031, 411);
            this.tblRelaciones.TabIndex = 0;
            this.pnlDisponibles.Controls.Add(this.lstDisponibles);
            this.pnlDisponibles.Controls.Add(this.txtBuscarDisponibles);
            this.pnlDisponibles.Controls.Add(this.lblDisponiblesCount);
            this.pnlDisponibles.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlDisponibles.Location = new System.Drawing.Point(3, 3);
            this.pnlDisponibles.Name = "pnlDisponibles";
            this.pnlDisponibles.Size = new System.Drawing.Size(483, 405);
            this.pnlDisponibles.TabIndex = 0;
            this.lstDisponibles.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lstDisponibles.Location = new System.Drawing.Point(0, 50);
            this.lstDisponibles.Name = "lstDisponibles";
            this.lstDisponibles.Size = new System.Drawing.Size(483, 355);
            this.lstDisponibles.TabIndex = 4;
            this.txtBuscarDisponibles.Dock = System.Windows.Forms.DockStyle.Top;
            this.txtBuscarDisponibles.Location = new System.Drawing.Point(0, 30);
            this.txtBuscarDisponibles.Name = "txtBuscarDisponibles";
            this.txtBuscarDisponibles.Size = new System.Drawing.Size(483, 20);
            this.txtBuscarDisponibles.TabIndex = 2;
            this.lblDisponiblesCount.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblDisponiblesCount.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblDisponiblesCount.Location = new System.Drawing.Point(0, 0);
            this.lblDisponiblesCount.Name = "lblDisponiblesCount";
            this.lblDisponiblesCount.Padding = new System.Windows.Forms.Padding(5);
            this.lblDisponiblesCount.Size = new System.Drawing.Size(483, 30);
            this.lblDisponiblesCount.TabIndex = 0;
            this.lblDisponiblesCount.Text = "Inventario_DetalleEquipo_LabelDisponibles";
            this.lblDisponiblesCount.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.pnlBotonesRelacion.Controls.Add(this.btnAgregar);
            this.pnlBotonesRelacion.Controls.Add(this.btnQuitar);
            this.pnlBotonesRelacion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlBotonesRelacion.Location = new System.Drawing.Point(492, 3);
            this.pnlBotonesRelacion.Name = "pnlBotonesRelacion";
            this.pnlBotonesRelacion.Size = new System.Drawing.Size(45, 405);
            this.pnlBotonesRelacion.TabIndex = 1;
            this.btnAgregar.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnAgregar.Location = new System.Drawing.Point(2, 170);
            this.btnAgregar.Name = "btnAgregar";
            this.btnAgregar.Size = new System.Drawing.Size(40, 40);
            this.btnAgregar.TabIndex = 6;
            this.btnAgregar.Text = ">";
            this.btnAgregar.UseVisualStyleBackColor = true;
            this.btnAgregar.Click += new System.EventHandler(this.btnAgregar_Click);
            this.btnQuitar.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnQuitar.Location = new System.Drawing.Point(2, 220);
            this.btnQuitar.Name = "btnQuitar";
            this.btnQuitar.Size = new System.Drawing.Size(40, 40);
            this.btnQuitar.TabIndex = 7;
            this.btnQuitar.Text = "<";
            this.btnQuitar.UseVisualStyleBackColor = true;
            this.btnQuitar.Click += new System.EventHandler(this.btnQuitar_Click);
            this.pnlAsignados.Controls.Add(this.lstAsignados);
            this.pnlAsignados.Controls.Add(this.txtBuscarAsignados);
            this.pnlAsignados.Controls.Add(this.lblAsignadosCount);
            this.pnlAsignados.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlAsignados.Location = new System.Drawing.Point(543, 3);
            this.pnlAsignados.Name = "pnlAsignados";
            this.pnlAsignados.Size = new System.Drawing.Size(485, 405);
            this.pnlAsignados.TabIndex = 2;
            this.lstAsignados.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lstAsignados.Location = new System.Drawing.Point(0, 50);
            this.lstAsignados.Name = "lstAsignados";
            this.lstAsignados.Size = new System.Drawing.Size(485, 355);
            this.lstAsignados.TabIndex = 5;
            this.txtBuscarAsignados.Dock = System.Windows.Forms.DockStyle.Top;
            this.txtBuscarAsignados.Location = new System.Drawing.Point(0, 30);
            this.txtBuscarAsignados.Name = "txtBuscarAsignados";
            this.txtBuscarAsignados.Size = new System.Drawing.Size(485, 20);
            this.txtBuscarAsignados.TabIndex = 3;
            this.lblAsignadosCount.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblAsignadosCount.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblAsignadosCount.Location = new System.Drawing.Point(0, 0);
            this.lblAsignadosCount.Name = "lblAsignadosCount";
            this.lblAsignadosCount.Padding = new System.Windows.Forms.Padding(5);
            this.lblAsignadosCount.Size = new System.Drawing.Size(485, 30);
            this.lblAsignadosCount.TabIndex = 1;
            this.lblAsignadosCount.Text = "Inventario_DetalleEquipo_LabelAsignados";
            this.lblAsignadosCount.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGuardar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnGuardar.Location = new System.Drawing.Point(827, 546);
            this.btnGuardar.Name = "btnGuardar";
            this.btnGuardar.Size = new System.Drawing.Size(110, 35);
            this.btnGuardar.TabIndex = 1;
            this.btnGuardar.Text = "Inventario_DetalleEquipo_BotonGuardar";
            this.btnGuardar.Click += new System.EventHandler(this.btnGuardar_Click);
            this.btnCerrar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnCerrar.Location = new System.Drawing.Point(943, 546);
            this.btnCerrar.Name = "btnCerrar";
            this.btnCerrar.Size = new System.Drawing.Size(110, 35);
            this.btnCerrar.TabIndex = 0;
            this.btnCerrar.Text = "Inventario_DetalleEquipo_BotonCerrar";
            this.btnCerrar.Click += new System.EventHandler(this.btnCerrar_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.ClientSize = new System.Drawing.Size(1061, 591);
            this.Controls.Add(this.panelRelaciones);
            this.Controls.Add(this.panelInfo);
            this.Controls.Add(this.btnGuardar);
            this.Controls.Add(this.btnCerrar);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MinimumSize = new System.Drawing.Size(800, 550);
            this.Name = "FormDetalleEquipo";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Inventario_DetalleEquipo_Form_Titulo";
            this.Load += new System.EventHandler(this.FormDetalleEquipo_Load);
            this.panelInfo.ResumeLayout(false);
            this.tblInfo.ResumeLayout(false);
            this.tblInfo.PerformLayout();
            this.panelRelaciones.ResumeLayout(false);
            this.tblRelaciones.ResumeLayout(false);
            this.pnlDisponibles.ResumeLayout(false);
            this.pnlDisponibles.PerformLayout();
            this.pnlBotonesRelacion.ResumeLayout(false);
            this.pnlAsignados.ResumeLayout(false);
            this.pnlAsignados.PerformLayout();
            this.ResumeLayout(false);
        }
    }
}
