using System.Windows.Forms;
namespace TicketPro.Tecnico
{
    partial class FormGestionInventario
    {
        private System.ComponentModel.IContainer components = null;
        private TabControl tabInventario;
        private TabPage tabEquipos;
        private TabPage tabItems;
        private FlowLayoutPanel flowEquipos;
        private FlowLayoutPanel flowItems;
        private Panel panelSuperior;
        private Button btnAgregarEquipo;
        private Button btnAgregarItem;
        private Button btnLimpiarEquipo;
        private Button btnLimpiarItem;
        private Button btnExportarEquipos;
        private TextBox txtBuscarEquipo;
        private TextBox txtBuscarItem;
        private ComboBox cmbFiltroEquipo;
        private ComboBox cmbFiltroItem;
        private System.Windows.Forms.Label lblFiltroEquipos;
        private System.Windows.Forms.Label lblFiltroItems;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.tabInventario = new System.Windows.Forms.TabControl();
            this.tabEquipos = new System.Windows.Forms.TabPage();
            this.flowEquipos = new System.Windows.Forms.FlowLayoutPanel();
            this.tabItems = new System.Windows.Forms.TabPage();
            this.flowItems = new System.Windows.Forms.FlowLayoutPanel();
            this.panelSuperior = new System.Windows.Forms.Panel();
            this.btnExportarEquipos = new System.Windows.Forms.Button();
            this.lblFiltroEquipos = new System.Windows.Forms.Label();
            this.lblFiltroItems = new System.Windows.Forms.Label();
            this.cmbFiltroEquipo = new System.Windows.Forms.ComboBox();
            this.txtBuscarEquipo = new System.Windows.Forms.TextBox();
            this.cmbFiltroItem = new System.Windows.Forms.ComboBox();
            this.txtBuscarItem = new System.Windows.Forms.TextBox();
            this.btnAgregarEquipo = new System.Windows.Forms.Button();
            this.btnAgregarItem = new System.Windows.Forms.Button();
            this.btnLimpiarEquipo = new System.Windows.Forms.Button();
            this.btnLimpiarItem = new System.Windows.Forms.Button();
            this.tabInventario.SuspendLayout();
            this.tabEquipos.SuspendLayout();
            this.tabItems.SuspendLayout();
            this.panelSuperior.SuspendLayout();
            this.SuspendLayout();
            this.tabInventario.Controls.Add(this.tabEquipos);
            this.tabInventario.Controls.Add(this.tabItems);
            this.tabInventario.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabInventario.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.tabInventario.Location = new System.Drawing.Point(0, 107);
            this.tabInventario.Name = "tabInventario";
            this.tabInventario.SelectedIndex = 0;
            this.tabInventario.Size = new System.Drawing.Size(900, 493);
            this.tabInventario.TabIndex = 0;
            this.tabEquipos.Controls.Add(this.flowEquipos);
            this.tabEquipos.Location = new System.Drawing.Point(4, 24);
            this.tabEquipos.Name = "tabEquipos";
            this.tabEquipos.Padding = new System.Windows.Forms.Padding(3);
            this.tabEquipos.Size = new System.Drawing.Size(892, 465);
            this.tabEquipos.TabIndex = 0;
            this.tabEquipos.Text = "Inventario_Gestion_Tab_Equipos";
            this.tabEquipos.UseVisualStyleBackColor = true;
            this.flowEquipos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flowEquipos.Location = new System.Drawing.Point(3, 3);
            this.flowEquipos.Name = "flowEquipos";
            this.flowEquipos.Size = new System.Drawing.Size(886, 459);
            this.flowEquipos.TabIndex = 0;
            this.tabItems.Controls.Add(this.flowItems);
            this.tabItems.Location = new System.Drawing.Point(4, 24);
            this.tabItems.Name = "tabItems";
            this.tabItems.Padding = new System.Windows.Forms.Padding(3);
            this.tabItems.Size = new System.Drawing.Size(892, 465);
            this.tabItems.TabIndex = 1;
            this.tabItems.Text = "Inventario_Gestion_Tab_Items";
            this.tabItems.UseVisualStyleBackColor = true;
            this.flowItems.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flowItems.Location = new System.Drawing.Point(3, 3);
            this.flowItems.Name = "flowItems";
            this.flowItems.Size = new System.Drawing.Size(886, 459);
            this.flowItems.TabIndex = 1;
            this.panelSuperior.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.panelSuperior.Controls.Add(this.btnExportarEquipos);
            this.panelSuperior.Controls.Add(this.lblFiltroEquipos);
            this.panelSuperior.Controls.Add(this.lblFiltroItems);
            this.panelSuperior.Controls.Add(this.cmbFiltroEquipo);
            this.panelSuperior.Controls.Add(this.txtBuscarEquipo);
            this.panelSuperior.Controls.Add(this.cmbFiltroItem);
            this.panelSuperior.Controls.Add(this.txtBuscarItem);
            this.panelSuperior.Controls.Add(this.btnAgregarEquipo);
            this.panelSuperior.Controls.Add(this.btnAgregarItem);
            this.panelSuperior.Controls.Add(this.btnLimpiarEquipo);
            this.panelSuperior.Controls.Add(this.btnLimpiarItem);
            this.panelSuperior.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelSuperior.Location = new System.Drawing.Point(0, 0);
            this.panelSuperior.Name = "panelSuperior";
            this.panelSuperior.Padding = new System.Windows.Forms.Padding(10);
            this.panelSuperior.Size = new System.Drawing.Size(900, 107);
            this.panelSuperior.TabIndex = 1;
            this.btnExportarEquipos.BackColor = System.Drawing.Color.ForestGreen;
            this.btnExportarEquipos.FlatAppearance.BorderSize = 0;
            this.btnExportarEquipos.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnExportarEquipos.ForeColor = System.Drawing.Color.White;
            this.btnExportarEquipos.Location = new System.Drawing.Point(429, 15);
            this.btnExportarEquipos.Name = "btnExportarEquipos";
            this.btnExportarEquipos.Size = new System.Drawing.Size(100, 76);
            this.btnExportarEquipos.TabIndex = 10;
            this.btnExportarEquipos.Text = "Inventario_Gestion_BotonExportarEquipos";
            this.btnExportarEquipos.UseVisualStyleBackColor = false;
            this.lblFiltroEquipos.AutoSize = true;
            this.lblFiltroEquipos.ForeColor = System.Drawing.Color.White;
            this.lblFiltroEquipos.Location = new System.Drawing.Point(617, 8);
            this.lblFiltroEquipos.Name = "lblFiltroEquipos";
            this.lblFiltroEquipos.Size = new System.Drawing.Size(188, 13);
            this.lblFiltroEquipos.TabIndex = 0;
            this.lblFiltroEquipos.Text = "Inventario_Gestion_LabelFiltroEquipos";
            this.lblFiltroItems.AutoSize = true;
            this.lblFiltroItems.ForeColor = System.Drawing.Color.White;
            this.lblFiltroItems.Location = new System.Drawing.Point(617, 56);
            this.lblFiltroItems.Name = "lblFiltroItems";
            this.lblFiltroItems.Size = new System.Drawing.Size(175, 13);
            this.lblFiltroItems.TabIndex = 1;
            this.lblFiltroItems.Text = "Inventario_Gestion_LabelFiltroItems";
            this.cmbFiltroEquipo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbFiltroEquipo.Location = new System.Drawing.Point(617, 24);
            this.cmbFiltroEquipo.Name = "cmbFiltroEquipo";
            this.cmbFiltroEquipo.Size = new System.Drawing.Size(110, 21);
            this.cmbFiltroEquipo.TabIndex = 6;
            this.txtBuscarEquipo.Location = new System.Drawing.Point(737, 24);
            this.txtBuscarEquipo.Name = "txtBuscarEquipo";
            this.txtBuscarEquipo.Size = new System.Drawing.Size(150, 20);
            this.txtBuscarEquipo.TabIndex = 7;
            this.cmbFiltroItem.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbFiltroItem.Location = new System.Drawing.Point(617, 72);
            this.cmbFiltroItem.Name = "cmbFiltroItem";
            this.cmbFiltroItem.Size = new System.Drawing.Size(110, 21);
            this.cmbFiltroItem.TabIndex = 8;
            this.txtBuscarItem.Location = new System.Drawing.Point(737, 72);
            this.txtBuscarItem.Name = "txtBuscarItem";
            this.txtBuscarItem.Size = new System.Drawing.Size(150, 20);
            this.txtBuscarItem.TabIndex = 9;
            this.btnAgregarEquipo.Location = new System.Drawing.Point(20, 15);
            this.btnAgregarEquipo.Name = "btnAgregarEquipo";
            this.btnAgregarEquipo.Size = new System.Drawing.Size(120, 78);
            this.btnAgregarEquipo.TabIndex = 2;
            this.btnAgregarEquipo.Text = "Inventario_Gestion_BotonAgregarEquipo";
            this.btnAgregarItem.Location = new System.Drawing.Point(150, 15);
            this.btnAgregarItem.Name = "btnAgregarItem";
            this.btnAgregarItem.Size = new System.Drawing.Size(120, 78);
            this.btnAgregarItem.TabIndex = 3;
            this.btnAgregarItem.Text = "Inventario_Gestion_BotonAgregarItem";
            this.btnLimpiarEquipo.Location = new System.Drawing.Point(280, 15);
            this.btnLimpiarEquipo.Name = "btnLimpiarEquipo";
            this.btnLimpiarEquipo.Size = new System.Drawing.Size(143, 36);
            this.btnLimpiarEquipo.TabIndex = 4;
            this.btnLimpiarEquipo.Text = "Inventario_Gestion_BotonLimpiarEquipos";
            this.btnLimpiarItem.Location = new System.Drawing.Point(280, 56);
            this.btnLimpiarItem.Name = "btnLimpiarItem";
            this.btnLimpiarItem.Size = new System.Drawing.Size(143, 35);
            this.btnLimpiarItem.TabIndex = 5;
            this.btnLimpiarItem.Text = "Inventario_Gestion_BotonLimpiarItems";
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(900, 600);
            this.Controls.Add(this.tabInventario);
            this.Controls.Add(this.panelSuperior);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Sizable;
            this.Name = "FormGestionInventario";
            this.Text = "Inventario_Gestion_Form_Titulo";
            this.tabInventario.ResumeLayout(false);
            this.tabEquipos.ResumeLayout(false);
            this.tabItems.ResumeLayout(false);
            this.panelSuperior.ResumeLayout(false);
            this.panelSuperior.PerformLayout();
            this.ResumeLayout(false);
        }
    }
}
