using System.Drawing;
using System.Windows.Forms;
namespace TicketPro
{
    partial class CrearTicket
    {
        private System.ComponentModel.IContainer components = null;
        private Panel pnlHeader;
        private Label lblTituloForm;
        private Panel pnlBody;
        private TableLayoutPanel tblLayout;
        private Label lblTitulo;
        private TextBox TituloTxt;
        private Label lblDescripcion;
        private TextBox DescrTxt;
        private Label lblCategoria;
        private ComboBox cmbCategoria;
        private Label lblUbicacion;
        private ComboBox cmbUbicacion;
        private Label label1;     
        private ComboBox cmbTecnico;
        private Label label2;     
        private ComboBox cmbEquipo;
        private Label lblPrioridad;
        private ComboBox cmbPrioridad;
        private Panel pnlSLA;
        private Label lblPoliticaSLA;
        private Label lblFechaVencimiento;
        private Button button1;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }
        #region Codigo generado por el Disenador
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CrearTicket));
            this.pnlHeader = new System.Windows.Forms.Panel();
            this.lblTituloForm = new System.Windows.Forms.Label();
            this.pnlBody = new System.Windows.Forms.Panel();
            this.tblLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.TituloTxt = new System.Windows.Forms.TextBox();
            this.lblDescripcion = new System.Windows.Forms.Label();
            this.DescrTxt = new System.Windows.Forms.TextBox();
            this.lblCategoria = new System.Windows.Forms.Label();
            this.cmbCategoria = new System.Windows.Forms.ComboBox();
            this.lblUbicacion = new System.Windows.Forms.Label();
            this.cmbUbicacion = new System.Windows.Forms.ComboBox();
            this.label1 = new System.Windows.Forms.Label();
            this.cmbTecnico = new System.Windows.Forms.ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this.cmbEquipo = new System.Windows.Forms.ComboBox();
            this.lblPrioridad = new System.Windows.Forms.Label();
            this.cmbPrioridad = new System.Windows.Forms.ComboBox();
            this.pnlSLA = new System.Windows.Forms.Panel();
            this.lblPoliticaSLA = new System.Windows.Forms.Label();
            this.lblFechaVencimiento = new System.Windows.Forms.Label();
            this.button1 = new System.Windows.Forms.Button();
            this.pnlHeader.SuspendLayout();
            this.pnlBody.SuspendLayout();
            this.tblLayout.SuspendLayout();
            this.pnlSLA.SuspendLayout();
            this.SuspendLayout();
            this.pnlHeader.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.pnlHeader.Controls.Add(this.lblTituloForm);
            this.pnlHeader.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlHeader.Location = new System.Drawing.Point(0, 0);
            this.pnlHeader.Name = "pnlHeader";
            this.pnlHeader.Size = new System.Drawing.Size(800, 50);
            this.pnlHeader.TabIndex = 0;
            this.pnlHeader.MouseDown += new System.Windows.Forms.MouseEventHandler(this.pnlHeader_MouseDown);
            this.pnlHeader.MouseMove += new System.Windows.Forms.MouseEventHandler(this.pnlHeader_MouseMove);
            this.pnlHeader.MouseUp += new System.Windows.Forms.MouseEventHandler(this.pnlHeader_MouseUp);
            this.lblTituloForm.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTituloForm.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.lblTituloForm.ForeColor = System.Drawing.Color.White;
            this.lblTituloForm.Location = new System.Drawing.Point(0, 0);
            this.lblTituloForm.Name = "lblTituloForm";
            this.lblTituloForm.Size = new System.Drawing.Size(800, 50);
            this.lblTituloForm.TabIndex = 0;
            this.lblTituloForm.Text = "Crear Nuevo Ticket";
            this.lblTituloForm.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.pnlBody.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(65)))));
            this.pnlBody.Controls.Add(this.tblLayout);
            this.pnlBody.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlBody.Location = new System.Drawing.Point(0, 50);
            this.pnlBody.Name = "pnlBody";
            this.pnlBody.Padding = new System.Windows.Forms.Padding(20);
            this.pnlBody.Size = new System.Drawing.Size(800, 550);
            this.pnlBody.TabIndex = 1;
            this.tblLayout.ColumnCount = 2;
            this.tblLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tblLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tblLayout.Controls.Add(this.lblTitulo, 0, 0);
            this.tblLayout.Controls.Add(this.TituloTxt, 0, 1);
            this.tblLayout.Controls.Add(this.lblDescripcion, 0, 2);
            this.tblLayout.Controls.Add(this.DescrTxt, 0, 3);
            this.tblLayout.Controls.Add(this.lblCategoria, 0, 4);
            this.tblLayout.Controls.Add(this.cmbCategoria, 0, 5);
            this.tblLayout.Controls.Add(this.lblUbicacion, 1, 4);
            this.tblLayout.Controls.Add(this.cmbUbicacion, 1, 5);
            this.tblLayout.Controls.Add(this.label1, 0, 6);
            this.tblLayout.Controls.Add(this.cmbTecnico, 0, 7);
            this.tblLayout.Controls.Add(this.label2, 1, 6);
            this.tblLayout.Controls.Add(this.cmbEquipo, 1, 7);
            this.tblLayout.Controls.Add(this.lblPrioridad, 0, 8);
            this.tblLayout.Controls.Add(this.cmbPrioridad, 0, 9);
            this.tblLayout.Controls.Add(this.pnlSLA, 1, 8);
            this.tblLayout.Controls.Add(this.button1, 1, 10);
            this.tblLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tblLayout.Location = new System.Drawing.Point(20, 20);
            this.tblLayout.Name = "tblLayout";
            this.tblLayout.RowCount = 11;
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 100F));
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tblLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tblLayout.Size = new System.Drawing.Size(760, 510);
            this.tblLayout.TabIndex = 0;
            this.lblTitulo.AutoSize = true;
            this.tblLayout.SetColumnSpan(this.lblTitulo, 2);
            this.lblTitulo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitulo.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblTitulo.ForeColor = System.Drawing.Color.White;
            this.lblTitulo.Location = new System.Drawing.Point(3, 0);
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.Size = new System.Drawing.Size(754, 30);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.Text = "Titulo";
            this.lblTitulo.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.TituloTxt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.TituloTxt.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.tblLayout.SetColumnSpan(this.TituloTxt, 2);
            this.TituloTxt.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TituloTxt.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.TituloTxt.ForeColor = System.Drawing.Color.White;
            this.TituloTxt.Location = new System.Drawing.Point(3, 33);
            this.TituloTxt.Name = "TituloTxt";
            this.TituloTxt.Size = new System.Drawing.Size(754, 25);
            this.TituloTxt.TabIndex = 1;
            this.lblDescripcion.AutoSize = true;
            this.tblLayout.SetColumnSpan(this.lblDescripcion, 2);
            this.lblDescripcion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDescripcion.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblDescripcion.ForeColor = System.Drawing.Color.White;
            this.lblDescripcion.Location = new System.Drawing.Point(3, 65);
            this.lblDescripcion.Name = "lblDescripcion";
            this.lblDescripcion.Size = new System.Drawing.Size(754, 30);
            this.lblDescripcion.TabIndex = 2;
            this.lblDescripcion.Text = "Descripcion";
            this.lblDescripcion.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.DescrTxt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.DescrTxt.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.tblLayout.SetColumnSpan(this.DescrTxt, 2);
            this.DescrTxt.Dock = System.Windows.Forms.DockStyle.Fill;
            this.DescrTxt.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.DescrTxt.ForeColor = System.Drawing.Color.White;
            this.DescrTxt.Location = new System.Drawing.Point(3, 98);
            this.DescrTxt.Multiline = true;
            this.DescrTxt.Name = "DescrTxt";
            this.DescrTxt.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.DescrTxt.Size = new System.Drawing.Size(754, 94);
            this.DescrTxt.TabIndex = 3;
            this.lblCategoria.AutoSize = true;
            this.lblCategoria.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCategoria.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblCategoria.ForeColor = System.Drawing.Color.White;
            this.lblCategoria.Location = new System.Drawing.Point(3, 195);
            this.lblCategoria.Name = "lblCategoria";
            this.lblCategoria.Size = new System.Drawing.Size(374, 30);
            this.lblCategoria.TabIndex = 4;
            this.lblCategoria.Text = "Categoria";
            this.lblCategoria.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.cmbCategoria.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.cmbCategoria.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbCategoria.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCategoria.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbCategoria.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cmbCategoria.ForeColor = System.Drawing.Color.White;
            this.cmbCategoria.FormattingEnabled = true;
            this.cmbCategoria.Location = new System.Drawing.Point(3, 228);
            this.cmbCategoria.Name = "cmbCategoria";
            this.cmbCategoria.Size = new System.Drawing.Size(374, 25);
            this.cmbCategoria.TabIndex = 5;
            this.lblUbicacion.AutoSize = true;
            this.lblUbicacion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblUbicacion.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblUbicacion.ForeColor = System.Drawing.Color.White;
            this.lblUbicacion.Location = new System.Drawing.Point(383, 195);
            this.lblUbicacion.Name = "lblUbicacion";
            this.lblUbicacion.Size = new System.Drawing.Size(374, 30);
            this.lblUbicacion.TabIndex = 6;
            this.lblUbicacion.Text = "Ubicacion";
            this.lblUbicacion.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.cmbUbicacion.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.cmbUbicacion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbUbicacion.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbUbicacion.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbUbicacion.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cmbUbicacion.ForeColor = System.Drawing.Color.White;
            this.cmbUbicacion.FormattingEnabled = true;
            this.cmbUbicacion.Location = new System.Drawing.Point(383, 228);
            this.cmbUbicacion.Name = "cmbUbicacion";
            this.cmbUbicacion.Size = new System.Drawing.Size(374, 25);
            this.cmbUbicacion.TabIndex = 7;
            this.label1.AutoSize = true;
            this.label1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(3, 260);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(374, 30);
            this.label1.TabIndex = 8;
            this.label1.Text = "Tecnico";
            this.label1.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.cmbTecnico.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.cmbTecnico.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbTecnico.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbTecnico.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbTecnico.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cmbTecnico.ForeColor = System.Drawing.Color.White;
            this.cmbTecnico.FormattingEnabled = true;
            this.cmbTecnico.Location = new System.Drawing.Point(3, 293);
            this.cmbTecnico.Name = "cmbTecnico";
            this.cmbTecnico.Size = new System.Drawing.Size(374, 25);
            this.cmbTecnico.TabIndex = 9;
            this.cmbTecnico.SelectedIndexChanged += new System.EventHandler(this.cmbTecnico_SelectedIndexChanged);
            this.label2.AutoSize = true;
            this.label2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label2.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(383, 260);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(374, 30);
            this.label2.TabIndex = 10;
            this.label2.Text = "Equipo";
            this.label2.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.cmbEquipo.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.cmbEquipo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbEquipo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbEquipo.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbEquipo.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cmbEquipo.ForeColor = System.Drawing.Color.White;
            this.cmbEquipo.FormattingEnabled = true;
            this.cmbEquipo.Location = new System.Drawing.Point(383, 293);
            this.cmbEquipo.Name = "cmbEquipo";
            this.cmbEquipo.Size = new System.Drawing.Size(374, 25);
            this.cmbEquipo.TabIndex = 11;
            this.cmbEquipo.SelectedIndexChanged += new System.EventHandler(this.cmbEquipo_SelectedIndexChanged);
            this.lblPrioridad.AutoSize = true;
            this.lblPrioridad.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPrioridad.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblPrioridad.ForeColor = System.Drawing.Color.White;
            this.lblPrioridad.Location = new System.Drawing.Point(3, 325);
            this.lblPrioridad.Name = "lblPrioridad";
            this.lblPrioridad.Size = new System.Drawing.Size(374, 30);
            this.lblPrioridad.TabIndex = 12;
            this.lblPrioridad.Text = "Prioridad";
            this.lblPrioridad.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.cmbPrioridad.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.cmbPrioridad.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbPrioridad.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbPrioridad.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbPrioridad.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cmbPrioridad.ForeColor = System.Drawing.Color.White;
            this.cmbPrioridad.FormattingEnabled = true;
            this.cmbPrioridad.Location = new System.Drawing.Point(3, 358);
            this.cmbPrioridad.Name = "cmbPrioridad";
            this.cmbPrioridad.Size = new System.Drawing.Size(374, 25);
            this.cmbPrioridad.TabIndex = 13;
            this.cmbPrioridad.SelectedIndexChanged += new System.EventHandler(this.cmbPrioridad_SelectedIndexChanged);
            this.pnlSLA.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            this.pnlSLA.Controls.Add(this.lblPoliticaSLA);
            this.pnlSLA.Controls.Add(this.lblFechaVencimiento);
            this.pnlSLA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlSLA.Location = new System.Drawing.Point(383, 328);
            this.pnlSLA.Name = "pnlSLA";
            this.pnlSLA.Padding = new System.Windows.Forms.Padding(10);
            this.tblLayout.SetRowSpan(this.pnlSLA, 2);
            this.pnlSLA.Size = new System.Drawing.Size(374, 59);
            this.pnlSLA.TabIndex = 14;
            this.lblPoliticaSLA.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblPoliticaSLA.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblPoliticaSLA.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(180)))), ((int)(((byte)(255)))));
            this.lblPoliticaSLA.Location = new System.Drawing.Point(10, 32);
            this.lblPoliticaSLA.Name = "lblPoliticaSLA";
            this.lblPoliticaSLA.Size = new System.Drawing.Size(354, 22);
            this.lblPoliticaSLA.TabIndex = 0;
            this.lblPoliticaSLA.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblFechaVencimiento.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblFechaVencimiento.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblFechaVencimiento.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(220)))), ((int)(((byte)(100)))));
            this.lblFechaVencimiento.Location = new System.Drawing.Point(10, 10);
            this.lblFechaVencimiento.Name = "lblFechaVencimiento";
            this.lblFechaVencimiento.Size = new System.Drawing.Size(354, 22);
            this.lblFechaVencimiento.TabIndex = 1;
            this.lblFechaVencimiento.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.button1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(132)))), ((int)(((byte)(255)))));
            this.button1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.button1.FlatAppearance.BorderSize = 0;
            this.button1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button1.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold);
            this.button1.ForeColor = System.Drawing.Color.White;
            this.button1.Location = new System.Drawing.Point(597, 465);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(160, 42);
            this.button1.TabIndex = 15;
            this.button1.Text = "Crear Ticket";
            this.button1.UseVisualStyleBackColor = false;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.ClientSize = new System.Drawing.Size(800, 600);
            this.Controls.Add(this.pnlBody);
            this.Controls.Add(this.pnlHeader);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ForeColor = System.Drawing.Color.White;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MinimumSize = new System.Drawing.Size(650, 500);
            this.Name = "CrearTicket";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Crear Ticket - TicketsPro";
            this.Load += new System.EventHandler(this.CrearTicket_Load);
            this.pnlHeader.ResumeLayout(false);
            this.pnlBody.ResumeLayout(false);
            this.tblLayout.ResumeLayout(false);
            this.tblLayout.PerformLayout();
            this.pnlSLA.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
    }
}
